CREATE TABLE [dbo].[Hours] (
    [HoursId]           INT                           IDENTITY (1, 1) NOT NULL,
    [SSN]               [dbo].[UDT_SSN]               NULL,
    [LastName]          [dbo].[UDT_NAME]              NULL,
    [Firstname]         [dbo].[UDT_NAME]              NULL,
    [Middlename]        [dbo].[UDT_NAME]              NULL,
    [Period]            [dbo].[UDT_INT]               NOT NULL,
    [PensionYear]       [dbo].[UDT_INT]               NOT NULL,
    [ReportId]          [dbo].[UDT_INT]               NOT NULL,
    [UnionCode]         [dbo].[UDT_INT]               NOT NULL,
    [Class]             [dbo].[UDT_CODE_VALUE]        NULL,
    [Scale]             [dbo].[UDT_CODE_VALUE]        NULL,
    [Schedule]          [dbo].[UDT_CODE_VALUE]        NULL,
    [UnionMisc]         [dbo].[UDT_CODE_VALUE]        NULL,
    [HoursReported]     [dbo].[UDT_SERVICE]           NOT NULL,
    [HoursWorked]       [dbo].[UDT_SERVICE]           NOT NULL,
    [ProductionTitleId] [dbo].[UDT_INT]               NULL,
    [IAPReported]       [dbo].[UDT_SERVICE_TOTAL]     NOT NULL,
    [IAPValue]          [dbo].[UDT_SERVICE_TOTAL]     NULL,
    [HoursValue]        [dbo].[UDT_SERVICE_TOTAL]     NULL,
    [Accepted]          [dbo].[UDT_FLAG]              NOT NULL,
    [Eligibility]       [dbo].[UDT_FLAG]              NOT NULL,
    [Pension]           [dbo].[UDT_FLAG]              NOT NULL,
    [Status]            [dbo].[UDT_ID]                NOT NULL,
    [IAPStatus]         [dbo].[UDT_ID]                NOT NULL,
    [Reversed]          [dbo].[UDT_INT]               NULL,
    [IAPReversed]       [dbo].[UDT_INT]               NULL,
    [Comment]           [dbo].[UDT_DATA100]           NULL,
    [AuditDate]         [dbo].[UDT_DATETIME]          NOT NULL,
    [AuditUser]         [dbo].[UDT_SHORTDESC]         NOT NULL,
    [rowguid]           [dbo].[UDT_UNIQUE_IDENTIFIER] ROWGUIDCOL NOT NULL
);

