CREATE TABLE [dbo].[SGS_JOB_PARAMETERS] (
    [JOB_PARAMETERS_ID] [dbo].[UDT_IDENTITY]   IDENTITY (1, 1) NOT NULL,
    [JOB_DETAIL_ID]     [dbo].[UDT_ID]         NOT NULL,
    [PARAM_NAME]        [dbo].[UDT_DATA50]     NOT NULL,
    [PARAM_VALUE]       [dbo].[UDT_LONGDESC]   NOT NULL,
    [CREATED_BY]        [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]      [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]       [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]     [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]        [dbo].[UDT_UPDSEQ]     NOT NULL
);

