CREATE TABLE [dbo].[SGS_FILE] (
    [FILE_ID]                 [dbo].[UDT_IDENTITY]   NOT NULL,
    [DESCRIPTION]             [dbo].[UDT_DESC]       NULL,
    [DELIMITED_BY]            [dbo].[UDT_IND]        NULL,
    [TRANSACTION_CODE_POS]    [dbo].[UDT_INT]        NULL,
    [TRANSACTION_CODE_LENGTH] [dbo].[UDT_INT]        NULL,
    [TRANSACTION_CODE_VALUE]  [dbo].[UDT_LONGDESC]   NULL,
    [HEADER_GROUP_POS]        [dbo].[UDT_INT]        NULL,
    [HEADER_GROUP_LENGTH]     [dbo].[UDT_INT]        NULL,
    [XML_LAYOUT_FILE]         [dbo].[UDT_FILE_NAME]  NULL,
    [INBOUND_MASK]            [dbo].[UDT_DATA]       NULL,
    [MAILBOX_PATH_CODE]       [dbo].[UDT_DATA]       NULL,
    [STAGING_PATH_CODE]       [dbo].[UDT_DATA]       NULL,
    [ERROR_PATH_CODE]         [dbo].[UDT_DATA]       NULL,
    [PROCESS_PATH_CODE]       [dbo].[UDT_DATA]       NULL,
    [FILE_STATUS_ID]          [dbo].[UDT_CODE_ID]    NOT NULL,
    [FILE_STATUS_VALUE]       [dbo].[UDT_CODE_VALUE] NULL,
    [INBOUND_OUTBOUND_FLAG]   [dbo].[UDT_FLAG]       NOT NULL,
    [EMPLOYER_FLAG]           [dbo].[UDT_FLAG]       NOT NULL,
    [CREATED_BY]              [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]            [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]             [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]           [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]              [dbo].[UDT_UPDSEQ]     NOT NULL,
    [EMAIL_NOTIFICATION]      [dbo].[UDT_NOTES]      NULL,
    [OTHER_PARAMETERS]        [dbo].[UDT_DESC]       NULL,
    [GROUP_PROCESS_FLAG]      [dbo].[UDT_FLAG]       NOT NULL
);

