CREATE TABLE [dbo].[SGS_JOB_SCHEDULE] (
    [JOB_SCHEDULE_ID]                     [dbo].[UDT_IDENTITY]   IDENTITY (1, 1) NOT NULL,
    [SCHEDULE_NAME]                       [dbo].[UDT_LONGDESC]   NOT NULL,
    [ACTIVE_FLAG]                         [dbo].[UDT_FLAG]       NOT NULL,
    [FREQUENCY_TYPE_ID]                   [dbo].[UDT_CODE_ID]    NOT NULL,
    [FREQUENCY_TYPE_VALUE]                [dbo].[UDT_CODE_VALUE] NOT NULL,
    [FREQUENCY_INTERVAL]                  [dbo].[UDT_INT]        NOT NULL,
    [FREQ_SUBDAY_TYPE]                    [dbo].[UDT_INT]        NULL,
    [FREQ_SUBDAY_INTERVAL]                [dbo].[UDT_INT]        NULL,
    [FREQ_RELATIVE_INTERVAL]              [dbo].[UDT_INT]        NULL,
    [FREQ_RECURANCE_FACTOR]               [dbo].[UDT_INT]        NULL,
    [START_DATE]                          [dbo].[UDT_DATE]       NULL,
    [END_DATE]                            [dbo].[UDT_DATE]       NULL,
    [START_TIME]                          [dbo].[UDT_DATETIME]   NULL,
    [END_TIME]                            [dbo].[UDT_DATETIME]   NULL,
    [STATUS_ID]                           [dbo].[UDT_CODE_ID]    NULL,
    [STATUS_VALUE]                        [dbo].[UDT_CODE_VALUE] NULL,
    [CREATED_BY]                          [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]                        [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]                         [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]                       [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]                          [dbo].[UDT_UPDSEQ]     NOT NULL,
    [PRIORITY_ID]                         [dbo].[UDT_CODE_ID]    NULL,
    [PRIORITY_VALUE]                      [dbo].[UDT_CODE_VALUE] NULL,
    [CANCEL_PROCEDURE_NOTES]              [dbo].[UDT_COMMENTS]   NULL,
    [RESTART_PROCEDURE_NOTES]             [dbo].[UDT_COMMENTS]   NULL,
    [BATCH_STATUS_EMAIL_RECIPIENT_GROUPS] [dbo].[UDT_COMMENTS]   NULL,
    [BATCH_ERROR_EMAIL_RECIPIENT_GROUPS]  [dbo].[UDT_COMMENTS]   NULL,
    [EXECUTE_ON_ORG_HOLIDAY_FLAG]         [dbo].[UDT_FLAG]       NOT NULL,
    [SCHEDULE_CODE]                       [dbo].[UDT_SHORTNAME]  NULL,
    [CANCELLABLE_JOB_FLAG]                [dbo].[UDT_FLAG]       NOT NULL
);

