CREATE TABLE [dbo].[SGS_COR_TEMPLATES] (
    [TEMPLATE_ID]                 [dbo].[UDT_IDENTITY]   IDENTITY (1, 1) NOT NULL,
    [TEMPLATE_NAME]               [dbo].[UDT_DATA50]     NULL,
    [TEMPLATE_DESC]               [dbo].[UDT_COMMENTS]   NULL,
    [TEMPLATE_GROUP_ID]           [dbo].[UDT_CODE_ID]    NOT NULL,
    [TEMPLATE_GROUP_VALUE]        [dbo].[UDT_CODE_VALUE] NULL,
    [ACTIVE_FLAG]                 [dbo].[UDT_FLAG]       NOT NULL,
    [DESTINATION_ID]              [dbo].[UDT_CODE_ID]    NOT NULL,
    [DESTINATION_VALUE]           [dbo].[UDT_CODE_VALUE] NULL,
    [ASSOCIATED_FORMS]            [dbo].[UDT_DBOBJ]      NOT NULL,
    [FILTER_OBJECT_ID]            [dbo].[UDT_DATA]       NULL,
    [FILTER_OBJECT_FIELD]         [dbo].[UDT_DATA]       NULL,
    [FILTER_OBJECT_VALUE]         [dbo].[UDT_DATA]       NULL,
    [CONTACT_ROLE_ID]             [dbo].[UDT_CODE_ID]    NOT NULL,
    [CONTACT_ROLE_VALUE]          [dbo].[UDT_CODE_VALUE] NULL,
    [BATCH_FLAG]                  [dbo].[UDT_FLAG]       NOT NULL,
    [ONLINE_FLAG]                 [dbo].[UDT_FLAG]       NOT NULL,
    [AUTO_PRINT_FLAG]             [dbo].[UDT_FLAG]       NOT NULL,
    [PRINTER_NAME_ID]             [dbo].[UDT_CODE_ID]    NOT NULL,
    [PRINTER_NAME_VALUE]          [dbo].[UDT_CODE_VALUE] NULL,
    [CREATED_BY]                  [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]                [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]                 [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]               [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]                  [dbo].[UDT_UPDSEQ]     NOT NULL,
    [IMAGE_DOC_CATEGORY_ID]       [dbo].[UDT_CODE_ID]    NOT NULL,
    [IMAGE_DOC_CATEGORY_VALUE]    [dbo].[UDT_CODE_VALUE] NULL,
    [FILENET_DOCUMENT_TYPE_ID]    [dbo].[UDT_CODE_ID]    NOT NULL,
    [FILENET_DOCUMENT_TYPE_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
    [DOC_TYPE]               [dbo].[UDT_DATA50]     NULL
);

