CREATE TABLE [dbo].[SGS_USER] (
    [USER_SERIAL_ID]    [dbo].[UDT_IDENTITY]   IDENTITY (1, 1) NOT NULL,
    [USER_ID]           [dbo].[UDT_USERID]     NOT NULL,
    [PASSWORD]          [dbo].[UDT_PASSWD]     NULL,
    [FIRST_NAME]        [dbo].[UDT_NAME]       NULL,
    [MIDDLE_INITIAL]    [dbo].[UDT_IND]        NULL,
    [LAST_NAME]         [dbo].[UDT_NAME]       NULL,
    [BEGIN_DATE]        [dbo].[UDT_DATE]       NULL,
    [END_DATE]          [dbo].[UDT_DATE]       NULL,
    [EMAIL_ADDRESS]     [dbo].[UDT_EMAIL]      NULL,
    [USER_TYPE_ID]      [dbo].[UDT_CODE_ID]    NULL,
    [USER_TYPE_VALUE]   [dbo].[UDT_CODE_VALUE] NULL,
    [USER_STATUS_ID]    [dbo].[UDT_CODE_ID]    NULL,
    [USER_STATUS_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
    [PERSON_ID]         [dbo].[UDT_ID]         NULL,
    [LOG_ACTIVITY_FLAG] [dbo].[UDT_FLAG]       NULL,
    [INITIAL_PAGE]      [dbo].[UDT_DATA]       NULL,
    [COLOR_SCHEME]      [dbo].[UDT_DATA50]     NULL,
    [CREATED_BY]        [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]      [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]       [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]     [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]        [dbo].[UDT_UPDSEQ]     NOT NULL,
    [DIVISION_ID]       [dbo].[UDT_CODE_ID]    NULL,
    [DIVISION_VALUE]    [dbo].[UDT_CODE_VALUE] NULL,
    [ACCESS_TYPE_ID]    [dbo].[UDT_CODE_ID]    NULL,
    [ACCESS_TYPE_VALUE] [dbo].[UDT_CODE_VALUE] NULL
);

