CREATE TABLE [dbo].[SGS_PIR] (
    [PIR_ID]             [dbo].[UDT_IDENTITY]   IDENTITY (1, 1) NOT NULL,
    [STATUS_ID]          [dbo].[UDT_CODE_ID]    NOT NULL,
    [STATUS_VALUE]       [dbo].[UDT_CODE_VALUE] NULL,
    [PIR_DESCRIPTION]    [dbo].[UDT_LONGDESC]   NULL,
    [PRIORITY_ID]        [dbo].[UDT_CODE_ID]    NOT NULL,
    [PRIORITY_VALUE]     [dbo].[UDT_CODE_VALUE] NULL,
    [SEVERITY_ID]        [dbo].[UDT_CODE_ID]    NOT NULL,
    [SEVERITY_VALUE]     [dbo].[UDT_CODE_VALUE] NULL,
    [REPORTED_BY_ID]     [dbo].[UDT_CODE_ID]    NOT NULL,
    [ASSIGNED_TO_ID]     [dbo].[UDT_ID]         NULL,
    [SCREEN_AFFECTED]    [dbo].[UDT_DBOBJ]      NOT NULL,
    [OTHERUI_OBJECTS]    [dbo].[UDT_DBOBJ]      NOT NULL,
    [TESTCASE_SCENARIO]  VARCHAR (20)           NULL,
    [DEFECT_CAUSE_ID]    [dbo].[UDT_CODE_ID]    NOT NULL,
    [DEFECT_CAUSE_VALUE] [dbo].[UDT_CODE_VALUE] NOT NULL,
    [DATE_RESOLVED]      [dbo].[UDT_DATE]       NULL,
    [ENVIRONMENT_ID]     [dbo].[UDT_CODE_ID]    NULL,
    [ENVIRONMENT_VALUE]  [dbo].[UDT_CODE_VALUE] NULL,
    [TEST_PHASE_ID]      [dbo].[UDT_CODE_ID]    NULL,
    [TEST_PHASE_VALUE]   [dbo].[UDT_CODE_VALUE] NULL,
    [PROCESS_ID]         [dbo].[UDT_CODE_ID]    NULL,
    [PROCESS_VALUE]      [dbo].[UDT_CODE_VALUE] NULL,
    [DEFECT_RESOLUTION]  [dbo].[UDT_NOTES]      NULL,
    [CREATED_BY]         [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]       [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]        [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]      [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]         [dbo].[UDT_UPDSEQ]     NOT NULL,
    [RELEASE_INFO]       [dbo].[UDT_DATA]       NULL,
    [DUE_DATE]           [dbo].[UDT_DATE]       NULL,
    [LONG_DESCRIPTION]   [dbo].[UDT_COMMENTS]   NULL
);

