CREATE TABLE [dbo].[SGT_DRO_APPLICATION_STATUS_HISTORY](
	[DRO_APPLICATION_STATUS_HISTORY_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[DRO_APPLICATION_ID] [dbo].[UDT_ID] NOT NULL,
	[STATUS_ID] [dbo].[UDT_ID] NOT NULL,
	[STATUS_VALUE] [dbo].[UDT_CODE_VALUE] NOT NULL,
	[STATUS_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK_DRO_APPLICATION_STATUS_HISTORY] PRIMARY KEY CLUSTERED 
(
	[DRO_APPLICATION_STATUS_HISTORY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


