CREATE TABLE [dbo].[SGT_PERSON_BRIDGE_HOURS](
	[PERSON_BRIDGE_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[PERSON_ID] [dbo].[UDT_ID] NOT NULL,
	[BRIDGE_TYPE_ID] [dbo].[UDT_ID] NOT NULL,
	[BRIDGE_TYPE_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
	[HOURS_REPORTED] [dbo].[UDT_SERVICE] NULL,
	[COMPUTATION_YEAR] [dbo].[UDT_INT] NULL,
	[BRIDGE_START_DATE] [dbo].[UDT_DATETIME] NULL,
	[BRIDGE_END_DATE] [dbo].[UDT_DATETIME] NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK_PERSON_BRIDGE_HOURS] PRIMARY KEY CLUSTERED 
(
	[PERSON_BRIDGE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


