CREATE TABLE [dbo].[SGT_BENEFIT_PROVISION](
	[BENEFIT_PROVISION_ID] [int] IDENTITY(1,1) NOT NULL,
	[SHORT_DECRIPTION] [dbo].[UDT_DESC] NULL,
	[DESCRIPTION] [dbo].[UDT_LONGDESC] NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK__SGT_BENEFIT_PROVISION_ID] PRIMARY KEY CLUSTERED 
(
	[BENEFIT_PROVISION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


