CREATE TABLE [dbo].[SGT_ORG_ADDRESS] (
    [ORG_ADDRESS_ID]       [dbo].[UDT_IDENTITY]   IDENTITY (5001, 1) NOT NULL,
    [ORG_ID]               [dbo].[UDT_ID]         NOT NULL,
    [ADDRESS_TYPE_ID]      [dbo].[UDT_CODE_ID]    NULL,
    [ADDRESS_TYPE_VALUE]   [dbo].[UDT_CODE_VALUE] NULL,
    [ADDR_LINE_1]          [dbo].[UDT_ADDRESS]    NULL,
    [ADDR_LINE_2]          [dbo].[UDT_ADDRESS]    NULL,
    [CITY]                 [dbo].[UDT_CITY]       NULL,
    [STATE_ID]             [dbo].[UDT_CODE_ID]    NULL,
    [STATE_VALUE]          [dbo].[UDT_CODE_VALUE] NULL,
    [COUNTRY_ID]           [dbo].[UDT_CODE_ID]    NULL,
    [COUNTRY_VALUE]        [dbo].[UDT_CODE_VALUE] NULL,
    [ZIP_CODE]             [dbo].[UDT_ZIP5]       NULL,
    [ZIP_4_CODE]           [dbo].[UDT_ZIP4]       NULL,
    [START_DATE]           [dbo].[UDT_DATETIME]   NULL,
    [END_DATE]             [dbo].[UDT_DATETIME]   NULL,
    [PRIMARY_ADDR_FLAG]    [dbo].[UDT_FLAG]       NULL,
    [NON_DELIVERABLE_FLAG] [dbo].[UDT_FLAG]       NULL,
    [FOREIGN_PROVINCE]     [dbo].[UDT_TEXT]       NULL,
    [FOREIGN_POSTAL_CODE]  [dbo].[UDT_TEXT]       NULL,
    [STATUS_ID]            [dbo].[UDT_CODE_ID]    NULL,
    [STATUS_VALUE]         [dbo].[UDT_CODE_VALUE] NULL,
    [CREATED_BY]           [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]         [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]          [dbo].[UDT_CREATEDBY]  NOT NULL,
    [MODIFIED_DATE]        [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]           [dbo].[UDT_UPDSEQ]     NOT NULL
);

