CREATE TABLE [dbo].[SGT_DRO_APPLICATION] (
    [DRO_APPLICATION_ID] [dbo].[UDT_IDENTITY]   IDENTITY (1, 1) NOT NULL,
    [PERSON_ID]          [dbo].[UDT_ID]         NULL,
    [ALTERNATE_PAYEE_ID] [dbo].[UDT_ID]         NULL,
    [CASE_NUMBER]        [dbo].[UDT_DATA]       NULL,
    [RECEIVED_DATE]      [dbo].[UDT_DATETIME]   NULL,
    [DATE_OF_MARRIAGE]   [dbo].[UDT_DATETIME]   NULL,
    [DATE_OF_DIVORCE]    [dbo].[UDT_DATETIME]   NULL,
    [ORDER_DATE]         [dbo].[UDT_DATETIME]   NULL,
    [JOINDER_ON_FILE]    [dbo].[UDT_FLAG]       NULL,
    [JOINDER_RECV_DATE]  [dbo].[UDT_DATETIME]   NULL,
    [QUALIFIED_BY_USER]  [dbo].[UDT_CREATEDBY]  NULL,
    [QUALIFIED_DATE]     [dbo].[UDT_DATETIME]   NULL,
    [APPROVED_BY_USER]   [dbo].[UDT_CREATEDBY]  NULL,
    [APPROVED_DATE]      [dbo].[UDT_DATETIME]   NULL,
    [DRO_STATUS_ID]      [dbo].[UDT_ID]         NULL,
    [DRO_STATUS_VALUE]   [dbo].[UDT_CODE_VALUE] NULL,
    [STATUS_ID]          [dbo].[UDT_ID]         NULL,
    [STATUS_VALUE]       [dbo].[UDT_CODE_VALUE] NULL,
    [NOTES]              [dbo].[UDT_NOTES]      NULL,
    [CREATED_BY]         [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]       [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]        [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]      [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]         [dbo].[UDT_UPDSEQ]     NOT NULL,
    [IS_AMMENDED_FLAG]   [dbo].[UDT_FLAG]       NULL,
    [BATCH_90DAY_FLAG]   [dbo].[UDT_FLAG]       NULL
);

