CREATE TABLE [dbo].[SGT_DEATH_NOTIFICATION](
	[DEATH_NOTIFICATION_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[PERSON_ID] [dbo].[UDT_ID] NOT NULL,
	[DEATH_NOTIFICATION_STATUS_ID] [dbo].[UDT_ID] NULL,
	[DEATH_NOTIFICATION_STATUS_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
	[DATE_OF_DEATH] [dbo].[UDT_DATETIME] NULL,
	[DEATH_NOTIFICATION_RECEIVED_DATE] [dbo].[UDT_DATETIME] NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATE] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK_SGT_DEATH_NOTIFICATION_1] PRIMARY KEY CLUSTERED 
(
	[DEATH_NOTIFICATION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


