CREATE TABLE [dbo].[SGT_PERSON] (
    [PERSON_ID]                      INT                    IDENTITY (1, 1) NOT NULL,
    [MPI_PERSON_ID]                  [dbo].[UDT_DATA]       NOT NULL,
    [FIRST_NAME]                     [dbo].[UDT_NAME]       NULL,
    [MIDDLE_NAME]                    [dbo].[UDT_NAME]       NULL,
    [LAST_NAME]                      [dbo].[UDT_NAME]       NULL,
    [NAME_PREFIX_ID]                 [dbo].[UDT_ID]         NULL,
    [NAME_PREFIX_VALUE]              [dbo].[UDT_CODE_VALUE] NULL,
    [DATE_OF_BIRTH]                  [dbo].[UDT_DATETIME]   NULL,
    [DATE_OF_DEATH]                  [dbo].[UDT_DATETIME]   NULL,
    [SSN]                            [dbo].[UDT_SSN]        NULL,
    [ETHNICITY]                      [dbo].[UDT_NAME]       NULL,
    [GENDER_ID]                      [dbo].[UDT_ID]         NULL,
    [GENDER_VALUE]                   [dbo].[UDT_CODE_VALUE] NULL,
    [MARITAL_STATUS_ID]              [dbo].[UDT_ID]         NULL,
    [MARITAL_STATUS_VALUE]           [dbo].[UDT_CODE_VALUE] NULL,
    [HOME_PHONE_NO]                  [dbo].[UDT_PHONE]      NULL,
    [WORK_PHONE_NO]                  [dbo].[UDT_PHONE]      NULL,
    [CELL_PHONE_NO]                  [dbo].[UDT_PHONE]      NULL,
    [EXTENSION]                      [dbo].[UDT_PHONE]      NULL,
    [FAX_NO]                         [dbo].[UDT_FAX]        NULL,
    [PAGER]                          [dbo].[UDT_PHONE]      NULL,
    [EMAIL_ADDRESS_1]                [dbo].[UDT_EMAIL]      NULL,
    [EMAIL_ADDRESS_2]                [dbo].[UDT_EMAIL]      NULL,
    [COMMUNICATION_PREFERENCE_ID]    [dbo].[UDT_ID]         NULL,
    [COMMUNICATION_PREFERENCE_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
    [STATUS_ID]                      [dbo].[UDT_ID]         NULL,
    [STATUS_VALUE]                   [dbo].[UDT_CODE_VALUE] NULL,
    [CREATED_BY]                     [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]                   [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]                    [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]                  [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]                     [dbo].[UDT_UPDSEQ]     NOT NULL,
    [DATE_OF_MARRIAGE]               [dbo].[UDT_DATETIME]   NULL,
    [DATE_OF_DIVORCE]                [dbo].[UDT_DATETIME]   NULL,
    [VIP_FLAG]                       [dbo].[UDT_FLAG]       NULL,
    [NAME_SUFFIX]                    [dbo].[UDT_CODE]       NULL
);

