CREATE TABLE [dbo].[SGT_PERSON_ACCOUNT_ELIGIBILITY](
	[PERSON_ACCOUNT_ELIGIBILITY_ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSON_ACCOUNT_ID] [dbo].[UDT_ID] NULL,
	[VESTED_DATE] [dbo].[UDT_CREATEDBY] NOT NULL,
	[VESTING_RULE_ID] [dbo].[UDT_ID] NOT NULL,
	[FORFEITURE_DATE] [dbo].[UDT_CREATEDBY] NULL,
	[LAST_EVALUATED_DATE] [dbo].[UDT_CREATEDBY] NULL,
	[STATUS_ID] [dbo].[UDT_ID] NOT NULL,
	[STATUS_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK_PERSON_ACCOUNT_ELIGIBILITY_ID] PRIMARY KEY NONCLUSTERED 
(
	[PERSON_ACCOUNT_ELIGIBILITY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


