CREATE TABLE [dbo].[SGT_BENEFIT_PROVISION_BENEFIT_OPTION](
	[BENEFIT_PROVISION_BENEFIT_OPTION_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[BENEFIT_PROVISION_ID] [dbo].[UDT_ID] NOT NULL,
	[BENEFIT_OPTION_ID] [dbo].[UDT_ID] NOT NULL,
	[BENEFIT_OPTION_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
	[RETIREMENT_FLAG] [dbo].[UDT_FLAG] NULL,
	[WITHDRAWAL_FLAG] [dbo].[UDT_FLAG] NULL,
	[DISABILITY_FLAG] [dbo].[UDT_FLAG] NULL,
	[DEATH_FLAG] [dbo].[UDT_FLAG] NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK_SGT_BENEFIT_PROVISION_BENEFIT_OPTION] PRIMARY KEY CLUSTERED 
(
	[BENEFIT_PROVISION_BENEFIT_OPTION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


