CREATE TABLE [dbo].[SGT_ATTORNEY] (
    [ATTORNEY_ID]         [dbo].[UDT_IDENTITY]   IDENTITY (1, 1) NOT NULL,
    [FIRST_NAME]          [dbo].[UDT_NAME]       NULL,
    [LAST_NAME]           [dbo].[UDT_NAME]       NULL,
    [MIDDLE_NAME]         [dbo].[UDT_NAME]       NULL,
    [ADDR_LINE_1]         [dbo].[UDT_ADDRESS]    NULL,
    [ADDR_LINE_2]         [dbo].[UDT_ADDRESS]    NULL,
    [ADDR_CITY]           [dbo].[UDT_CITY]       NULL,
    [ADDR_STATE_ID]       [dbo].[UDT_ID]         NULL,
    [ADDR_STATE_VALUE]    [dbo].[UDT_CODE_VALUE] NULL,
    [ADDR_COUNTRY_ID]     [dbo].[UDT_ID]         NULL,
    [ADDR_COUNTRY_VALUE]  [dbo].[UDT_CODE_VALUE] NULL,
    [ADDR_ZIP_CODE]       [dbo].[UDT_INT]        NULL,
    [ADDR_ZIP_4_CODE]     [dbo].[UDT_INT]        NULL,
    [PHONE_NBR]           [dbo].[UDT_PHONE]      NULL,
    [EMAIL_ADDRESS]       [dbo].[UDT_EMAIL]      NULL,
    [ADDR_TYPE_ID]        [dbo].[UDT_ID]         NULL,
    [ADDR_TYPE_VALUE]     [dbo].[UDT_CODE_VALUE] NULL,
    [CONTACT_TYPE_ID]     [dbo].[UDT_ID]         NULL,
    [CONTACT_TYPE_VALUE]  [dbo].[UDT_CODE_VALUE] NULL,
    [ATTORNEY_TYPE_ID]    [dbo].[UDT_ID]         NULL,
    [ATTORNEY_TYPE_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
    [DATE_EFF_FROM]       [dbo].[UDT_DATETIME]   NULL,
    [DATE_EFF_TO]         [dbo].[UDT_DATETIME]   NULL,
    [DRO_APPLICATION_ID]  [dbo].[UDT_ID]         NULL,
    [CREATED_BY]          [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]        [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]         [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]       [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]          [dbo].[UDT_UPDSEQ]     NOT NULL
);

