CREATE TABLE [dbo].[Unions] (
    [UnionCode]      INT                    IDENTITY (1, 1) NOT NULL,
    [Name]           [dbo].[UDT_DATA100]    NOT NULL,
    [Description]    [dbo].[UDT_DATA100]    NULL,
    [UnionGroupCode] [dbo].[UDT_DATA]       NULL,
    [Inception]      [dbo].[UDT_DATETIME]   NULL,
    [LocalNumber]    [dbo].[UDT_INT]        NOT NULL,
    [Defunct]        [dbo].[UDT_DATETIME]   NULL,
    [Address1]       [dbo].[UDT_ADDRESS]    NULL,
    [EmployerId]     [dbo].[UDT_ID]         NULL,
    [Attention]      [dbo].[UDT_NAME]       NULL,
    [City]           [dbo].[UDT_CITY]       NULL,
    [State]          [dbo].[UDT_CODE_VALUE] NULL,
    [Address2]       [dbo].[UDT_ADDRESS]    NULL,
    [PostalCode]     [dbo].[UDT_DATA]       NULL,
    [AltAttention]   [dbo].[UDT_NAME]       NULL,
    [AltAddress1]    [dbo].[UDT_ADDRESS]    NULL,
    [Phone1]         [dbo].[UDT_DATA]       NULL,
    [AltAddress2]    [dbo].[UDT_ADDRESS]    NULL,
    [Phone2]         [dbo].[UDT_DATA]       NULL,
    [AltCity]        [dbo].[UDT_CITY]       NULL,
    [AltState]       [dbo].[UDT_CODE_VALUE] NULL,
    [EMail1]         [dbo].[UDT_ADDRESS]    NULL,
    [EMail2]         [dbo].[UDT_ADDRESS]    NULL,
    [AltPostalCode]  [dbo].[UDT_DATA]       NULL,
    [AuditDate]      [dbo].[UDT_DATA40]     NOT NULL,
    [AuditUser]      [dbo].[UDT_DATA40]     NOT NULL,
    [Fax1]           [dbo].[UDT_DATA]       NULL,
    [Fax2]           [dbo].[UDT_DATA]       NULL
);

