


CREATE PROCEDURE [dbo].[SGP_PROCESS_LOG_INSERT] ( @CYCLE_NO int , 
	@PROCESS_NAME VARCHAR(50) , 
	@MESSAGE_TYPE_VALUE VARCHAR(4) , 
	@MESSAGE VARCHAR(4096) , 
	@CREATED_BY VARCHAR(50) ) 
as
BEGIN 
	INSERT INTO SGS_PROCESS_LOG 
	( CYCLE_NO , PROCESS_NAME , MESSAGE_TYPE_ID , MESSAGE_TYPE_VALUE , MESSAGE , CREATED_BY , CREATED_DATE ) 
	VALUES 
	( @CYCLE_NO , @PROCESS_NAME , 28 , @MESSAGE_TYPE_VALUE , @MESSAGE , @CREATED_BY , getdate() ) 
END   



