CREATE CLUSTERED INDEX [CIX_SGS_AUDIT_LOG_DETAIL_AUDIT_LOG_ID]
    ON [dbo].[SGS_AUDIT_LOG_DETAIL]([AUDIT_LOG_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

