CREATE NONCLUSTERED INDEX [IX_SGS_USER_DEFAULTS_USER_SERIAL_ID]
    ON [dbo].[SGS_USER_DEFAULTS]([USER_SERIAL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

