ALTER TABLE [dbo].[SGT_BENEFIT_PROVISION_ELIGIBILITY]  WITH CHECK ADD  CONSTRAINT [FK_SGT_BENEFIT_PROVISION_ELIGIBILITY_SGT_BENEFIT_PROVISION] FOREIGN KEY([BENEFIT_PROVISION_ID])
REFERENCES [dbo].[SGT_BENEFIT_PROVISION] ([BENEFIT_PROVISION_ID])


GO
ALTER TABLE [dbo].[SGT_BENEFIT_PROVISION_ELIGIBILITY] CHECK CONSTRAINT [FK_SGT_BENEFIT_PROVISION_ELIGIBILITY_SGT_BENEFIT_PROVISION]

