ALTER TABLE [dbo].[SGW_ACTIVITY_INSTANCE]
    ADD CONSTRAINT [FK_SGW_ACTIVITY_INSTANCE_SGW_ACTIVITY] FOREIGN KEY ([ACTIVITY_ID]) REFERENCES [dbo].[SGW_ACTIVITY] ([ACTIVITY_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

