ALTER TABLE [dbo].[SGW_PROCESS_INSTANCE_PARAMETERS]
    ADD CONSTRAINT [FK_SGW_PROCESS_INSTANCE_PARAMETERS_SGW_PROCESS_INSTANCE] FOREIGN KEY ([PROCESS_INSTANCE_ID]) REFERENCES [dbo].[SGW_PROCESS_INSTANCE] ([PROCESS_INSTANCE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

