ALTER TABLE [dbo].[SGT_BENEFIT_PROVISION_BENEFIT_OPTION]  WITH CHECK ADD  CONSTRAINT [FK_SGT_BENEFIT_PROVISION_BENEFIT_OPTION_SGT_BENEFIT_PROVISION] FOREIGN KEY([BENEFIT_PROVISION_ID])
REFERENCES [dbo].[SGT_BENEFIT_PROVISION] ([BENEFIT_PROVISION_ID])


GO
ALTER TABLE [dbo].[SGT_BENEFIT_PROVISION_BENEFIT_OPTION] CHECK CONSTRAINT [FK_SGT_BENEFIT_PROVISION_BENEFIT_OPTION_SGT_BENEFIT_PROVISION]

