ALTER TABLE [dbo].[SGW_PROCESS_INSTANCE]
    ADD CONSTRAINT [FK_SGW_PROCESS_INSTANCE_SGW_PROCESS] FOREIGN KEY ([PROCESS_ID]) REFERENCES [dbo].[SGW_PROCESS] ([PROCESS_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

