ALTER TABLE [dbo].[SGW_WORKFLOW_REQUEST]
    ADD CONSTRAINT [FK_SGW_WORKFLOW_REQUEST_SGW_PROCESS] FOREIGN KEY ([PROCESS_ID]) REFERENCES [dbo].[SGW_PROCESS] ([PROCESS_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

