ALTER TABLE [dbo].[SGW_ACTIVITY_INSTANCE_HISTORY]
    ADD CONSTRAINT [FK_SGW_ACTIVITY_INSTANCE_HISTORY_SGW_ACTIVITY_INSTANCE] FOREIGN KEY ([ACTIVITY_INSTANCE_ID]) REFERENCES [dbo].[SGW_ACTIVITY_INSTANCE] ([ACTIVITY_INSTANCE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

