ALTER TABLE [dbo].[SGW_PROCESS_INSTANCE_CHECKLIST]
    ADD CONSTRAINT [FK_SGW_PROCESS_INSTANCE_CHECKLIST_SGT_DOCUMENT] FOREIGN KEY ([DOCUMENT_ID]) REFERENCES [dbo].[SGT_DOCUMENT] ([DOCUMENT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

