ALTER TABLE [dbo].[SGT_PERSON_ACCOUNT_BENEFICIARY_ERROR]
    ADD CONSTRAINT [PERSON_ACCOUNT_BENEFICIARY_ERROR_ID] PRIMARY KEY CLUSTERED ([PERSON_ACCOUNT_BENEFICIARY_ERROR_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

