ALTER TABLE [dbo].[Report]
    ADD CONSTRAINT [PK__Report__39E294A9] PRIMARY KEY CLUSTERED ([ReportId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

