ALTER TABLE [dbo].[Hours]
    ADD CONSTRAINT [PK__Hours__2116E6DF] PRIMARY KEY CLUSTERED ([HoursId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

