ALTER TABLE [dbo].[Unions]
    ADD CONSTRAINT [PK__Unions__2E70E1FD] PRIMARY KEY NONCLUSTERED ([UnionCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

