ALTER TABLE [dbo].[SGT_BENEFIT_APPLICATION_ERROR]
    ADD CONSTRAINT [PK_BENEFIT_APPLICATION_ERROR] PRIMARY KEY CLUSTERED ([BENEFIT_APPLICATION_ERROR_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

