ALTER TABLE [dbo].[SGT_DISABILITY_BENEFIT_HISTORY]
    ADD CONSTRAINT [PK_DISABILITY_BENEFIT_HISTORY] PRIMARY KEY CLUSTERED ([DISABILITY_BENEFIT_HISTORY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

