ALTER TABLE [dbo].[SGS_AUDIT_LOG]
    ADD CONSTRAINT [PK_SGS_AUDIT_LOG_AUDIT_LOG_ID] PRIMARY KEY CLUSTERED ([AUDIT_LOG_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

