ALTER TABLE [dbo].[SGS_JOB_DETAIL]
    ADD CONSTRAINT [PK_SGS_JOB_DETAIL_JOB_DETAIL_ID] PRIMARY KEY CLUSTERED ([JOB_DETAIL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

