ALTER TABLE [dbo].[SGS_TESTCASE_DETAIL]
    ADD CONSTRAINT [PK_SGS_TESTCASE_DETAIL] PRIMARY KEY CLUSTERED ([TESTCASE_DTL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

