ALTER TABLE [dbo].[SGW_WORKFLOW_REQUEST]
    ADD CONSTRAINT [PK_SGT_WF_IMAGE_DATA_FROM_FILENET] PRIMARY KEY CLUSTERED ([WORKFLOW_REQUEST_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

