ALTER TABLE [dbo].[SGS_ROLES]
    ADD CONSTRAINT [PK_SGS_ROLES_ROLE_ID] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

