ALTER TABLE [dbo].[SGT_PERSON_ADDRESS_HISTORY]
    ADD CONSTRAINT [PK_SGT_PERSON_ADDRESS_HISTORY] PRIMARY KEY CLUSTERED ([PERSON_ADDRESS_HISTORY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

