ALTER TABLE [dbo].[SGS_FILE_HDR]
    ADD CONSTRAINT [PK_SGS_FILE_HDR_FILE_HDR_ID] PRIMARY KEY CLUSTERED ([FILE_HDR_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

