ALTER TABLE [dbo].[SGS_HOLIDAY]
    ADD CONSTRAINT [PK_SGS_HOLIDAY_HOLIDAY_ID] PRIMARY KEY CLUSTERED ([HOLIDAY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

