ALTER TABLE [dbo].[SGT_QDRO_APPLICATION]
    ADD CONSTRAINT [PK_SGT_QDRO_APPLICATION] PRIMARY KEY CLUSTERED ([DRO_APPLICATION_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

