ALTER TABLE [dbo].[SGS_BATCH_SCHEDULE]
    ADD CONSTRAINT [PK_SGS_BATCH_SCHEDULE_BATCH_SCHEDULE_ID] PRIMARY KEY CLUSTERED ([BATCH_SCHEDULE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

