ALTER TABLE [dbo].[SGT_ORG_ADDRESS]
    ADD CONSTRAINT [PK_SGT_ORG_ADDRESS_ORG_ADDRESS_ID] PRIMARY KEY NONCLUSTERED ([ORG_ADDRESS_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

