ALTER TABLE [dbo].[SGS_BATCH_PARAMETERS]
    ADD CONSTRAINT [PK_SGS_BATCH_PARAMETERS] PRIMARY KEY CLUSTERED ([BATCH_PARAMETERS_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

