ALTER TABLE [dbo].[SGS_FILE_DTL]
    ADD CONSTRAINT [PK_SGS_FILE_DTL] PRIMARY KEY CLUSTERED ([FILE_DTL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

