ALTER TABLE [dbo].[SGT_NOTES]
    ADD CONSTRAINT [PK_SGT_NOTES] PRIMARY KEY CLUSTERED ([NOTE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

