ALTER TABLE [dbo].[SGS_SECURITY]
    ADD CONSTRAINT [PK_SGS_SECURITY_ROLE_ID_RESOURCE_ID_SECURITY_ID_SECURITY_VALUE] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC, [RESOURCE_ID] ASC, [SECURITY_ID] ASC, [SECURITY_VALUE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

