ALTER TABLE [dbo].[SGS_USER_ROLES]
    ADD CONSTRAINT [PK_SGS_USER_ROLES_USER_SERIAL_ID_ROLE_ID] PRIMARY KEY CLUSTERED ([USER_SERIAL_ID] ASC, [ROLE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

