ALTER TABLE [dbo].[SGS_FILE_DTL_ERROR]
    ADD CONSTRAINT [PK_SGS_FILE_DTL_ERROR_FILE_DTL_ERROR_ID] PRIMARY KEY NONCLUSTERED ([ERROR_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

