ALTER TABLE [dbo].[SGT_BATCH_NOTIFICATION]
    ADD CONSTRAINT [PK_SGT_BATCH_NOTIFICATION_BATCH_NOTIFICATION_ID] PRIMARY KEY CLUSTERED ([BATCH_NOTIFICATION_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

