ALTER TABLE [dbo].[SGW_ACTIVITY_INSTANCE_HISTORY]
    ADD CONSTRAINT [PK_SGT_ACTIVITY_INSTANCE_HISTORY1] PRIMARY KEY CLUSTERED ([ACTIVITY_INSTANCE_HISTORY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

