ALTER TABLE [dbo].[SGS_TESTCASE]
    ADD CONSTRAINT [PK_SGS_TESTCASE] PRIMARY KEY CLUSTERED ([TESTCASE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

