ALTER TABLE [dbo].[SGS_COR_TRACKING]
    ADD CONSTRAINT [PK_SGS_COR_TRACKING_TRACKING_ID] PRIMARY KEY CLUSTERED ([TRACKING_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

