ALTER TABLE [dbo].[SGT_PLAN]
    ADD CONSTRAINT [PK_SGT_PLAN] PRIMARY KEY CLUSTERED ([PLAN_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

