ALTER TABLE [dbo].[SGT_RELATIONSHIP]
    ADD CONSTRAINT [PK_SGT_RELATIONSHIP] PRIMARY KEY CLUSTERED ([PERSON_RELATIONSHIP_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

