ALTER TABLE [dbo].[SGS_USER]
    ADD CONSTRAINT [PK_SGS_USER_USER_SERIAL_ID] PRIMARY KEY CLUSTERED ([USER_SERIAL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

