ALTER TABLE [dbo].[SGS_CYCLE_HISTORY]
    ADD CONSTRAINT [PK_SGS_CYCLE_HISTORY_CYCLE_NO] PRIMARY KEY CLUSTERED ([CYCLE_NO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

