ALTER TABLE [dbo].[SGS_PIR]
    ADD CONSTRAINT [PK_SGS_PIR] PRIMARY KEY CLUSTERED ([PIR_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

