ALTER TABLE [dbo].[SGS_USER_SECURITY_HISTORY]
    ADD CONSTRAINT [PK_SGS_USER_SECURITY_HISTORY] PRIMARY KEY CLUSTERED ([SGS_USER_SECURITY_HISTORY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

