ALTER TABLE [dbo].[SGS_CUSTOM_SECURITY]
    ADD CONSTRAINT [PK_SGS_CUSTOM_SECURITY] PRIMARY KEY CLUSTERED ([CUSTOM_SECURITY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

