ALTER TABLE [dbo].[SGW_PROCESS_INSTANCE_IMAGE_DATA]
    ADD CONSTRAINT [PK_SGT_WF_IMAGE_DATA] PRIMARY KEY CLUSTERED ([PROCESS_INSTANCE_IMAGE_DATA_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

