ALTER TABLE [dbo].[SGW_PROCESS]
    ADD CONSTRAINT [PK_SGW_PROCESS] PRIMARY KEY CLUSTERED ([PROCESS_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

