ALTER TABLE [dbo].[SGS_SYSTEM_MANAGEMENT]
    ADD CONSTRAINT [PK_SGS_SYSTEM_MANAGEMENT_SYSTEM_MANAGEMENT_ID] PRIMARY KEY CLUSTERED ([SYSTEM_MANAGEMENT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

