ALTER TABLE [dbo].[SGS_JOB_SCHEDULE_DETAIL_ERROR]
    ADD CONSTRAINT [PK_SGS_JOB_SCHEDULE_DETAIL_ERROR_JOB_SCHEDULE_DETAIL_ERROR_ID] PRIMARY KEY CLUSTERED ([JOB_SCHEDULE_DETAIL_ERROR_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

