ALTER TABLE [dbo].[SGS_SYSTEM_PATHS]
    ADD CONSTRAINT [PK_SGS_SYSTEM_PATHS_1] PRIMARY KEY CLUSTERED ([PATH_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

