ALTER TABLE [dbo].[SGS_RESOURCES]
    ADD CONSTRAINT [PK_SGS_RESOURCES_RESOURCE_ID] PRIMARY KEY CLUSTERED ([RESOURCE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

