ALTER TABLE [dbo].[SGT_ORG_CONTACT]
    ADD CONSTRAINT [PK_SGT_ORG_CONTACT_ORG_CONTACT_ID] PRIMARY KEY NONCLUSTERED ([ORG_CONTACT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

