ALTER TABLE [dbo].[SGT_PLAN_BENEFIT_XR]
    ADD CONSTRAINT [PK_SGT_PLAN_BENEFIT] PRIMARY KEY CLUSTERED ([PLAN_BENEFIT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

