ALTER TABLE [dbo].[SGT_ORGANIZATION]
    ADD CONSTRAINT [PK_SGT_ORGANIZATION] PRIMARY KEY CLUSTERED ([ORG_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

