ALTER TABLE [dbo].[SGS_AUDIT_LOG_DETAIL]
    ADD CONSTRAINT [PK_SGS_AUDIT_LOG_DETAIL_AUDIT_LOG_DETAIL_ID] PRIMARY KEY NONCLUSTERED ([AUDIT_LOG_DETAIL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

