ALTER TABLE [dbo].[SGS_CODE_VALUE]
    ADD CONSTRAINT [PK_SGS_CODE_VALUE_CODE_SERIAL_ID] PRIMARY KEY NONCLUSTERED ([CODE_SERIAL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

