ALTER TABLE [dbo].[SGT_DRO_BENEFIT_DETAILS]
    ADD CONSTRAINT [PK_SGT_DRO_BENEFIT] PRIMARY KEY CLUSTERED ([DRO_BENEFIT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

