ALTER TABLE [dbo].[SGT_PERSON_BENEFICIARY]
    ADD CONSTRAINT [PK_SGT_PERSON_BENEFICIARY] PRIMARY KEY CLUSTERED ([BENEFICIARY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

