ALTER TABLE [dbo].[SGS_JOB_HEADER]
    ADD CONSTRAINT [PK_SGS_JOB_HEADER_JOB_HEADER_ID] PRIMARY KEY CLUSTERED ([JOB_HEADER_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

