ALTER TABLE [dbo].[SGS_CODE]
    ADD CONSTRAINT [PK_SGS_CODE_CODE_ID] PRIMARY KEY CLUSTERED ([CODE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

