ALTER TABLE [dbo].[SGW_PROCESS_INSTANCE_CHECKLIST]
    ADD CONSTRAINT [PK_SGT_PROCESS_INSTANCE_CHECKLIST] PRIMARY KEY CLUSTERED ([PROCESS_INSTANCE_CHECKLIST_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

