ALTER TABLE [dbo].[SGW_PROCESS_INSTANCE_PARAMETERS]
    ADD CONSTRAINT [PK_SGW_PROCESS_INSTANCE_PARAMETERS] PRIMARY KEY CLUSTERED ([PROCESS_INSTANCE_PARAMETER_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

