ALTER TABLE [dbo].[SGT_PERSON_CONTACT]
    ADD CONSTRAINT [PK_SGT_PERSON_CONTACT] PRIMARY KEY CLUSTERED ([PERSON_CONTACT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

