ALTER TABLE [dbo].[SGT_DOCUMENT_PROCESS_CROSSREF]
    ADD CONSTRAINT [PK_SGT_DOCUMENT_PROCESS_CROSSREF] PRIMARY KEY CLUSTERED ([DOCUMENT_PROCESS_CROSSREF_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

