ALTER TABLE [dbo].[SGW_INSTANCE_DEFINITION]
    ADD CONSTRAINT [PK_WorkflowDefinition] PRIMARY KEY CLUSTERED ([WORKFLOW_INSTANCE_GUID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

