ALTER TABLE [dbo].[SGS_COR_TRACKING_DETAIL]
    ADD CONSTRAINT [SGS_COR_TRACKING_DETAIL_PK] PRIMARY KEY CLUSTERED ([TRACKING_DETAIL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

