ALTER TABLE [dbo].[SGT_PERSON_ADDRESS_CHKLIST_HISTORY]
    ADD CONSTRAINT [SGT_PERSON_ADDRESS_CHKLIST_HISTORY_PK] PRIMARY KEY CLUSTERED ([ADDRESS_CHKLIST_HISTORY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

