ALTER TABLE [dbo].[SGW_ACTIVITY]
    ADD CONSTRAINT [SGT_ACTIVITY_PK] PRIMARY KEY CLUSTERED ([ACTIVITY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

