ALTER TABLE [dbo].[SGW_ACTIVITY_INSTANCE]
    ADD CONSTRAINT [SGW_ACTIVITY_INSTANCE_PK] PRIMARY KEY CLUSTERED ([ACTIVITY_INSTANCE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

