ALTER TABLE [dbo].[SGS_CODE_VALUE]
    ADD CONSTRAINT [UK_SGS_CODE_VALUE_CODE_ID_CODE_VALUE] UNIQUE CLUSTERED ([CODE_ID] ASC, [CODE_VALUE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

