ALTER TABLE [dbo].[SGT_BATCH_NOTIFICATION]
    ADD CONSTRAINT [UK_SGT_BATCH_NOTIFICATION_NOTIFICATION_ID] UNIQUE NONCLUSTERED ([NOTIFICATION_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

