-- =============================================
-- Script Template
-- =============================================

--Puneet Punjabi Calculation Scripts 

-- UDT_DATA_TYPES FOR PENSION CALCULATIONS

/****** Object:  UserDefinedDataType [dbo].[UDT_AGE_DEC]    Script Date: 01/25/2012 09:45:29 ******/
CREATE TYPE [dbo].[UDT_AGE_DEC] FROM [numeric](7, 4) NULL
GO

/****** Object:  UserDefinedDataType [dbo].[UDT_HOURS]    Script Date: 01/25/2012 09:45:29 ******/
CREATE TYPE [dbo].[UDT_HOURS] FROM [numeric](14, 4) NULL
GO

-- 1. SGT_BENEFIT_CALCULATION_HEADER
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_BENEFIT_CALCULATION_HEADER')
BEGIN 
	PRINT 'TABLE SGT_BENEFIT_CALCULATION_HEADER ALREADY EXISTS.'
	DROP TABLE SGT_BENEFIT_CALCULATION_HEADER
END
	PRINT 'CREATING TABLE - SGT_BENEFIT_CALCULATION_HEADER'
	CREATE TABLE SGT_BENEFIT_CALCULATION_HEADER (	BENEFIT_CALCULATION_HEADER_ID	DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
													BENEFIT_APPLICATION_ID			DBO.UDT_ID NULL,
													PERSON_ID						DBO.UDT_ID NOT NULL,
													BENEFICIARY_PERSON_ID			DBO.UDT_ID NULL,
													BENEFICIARY_PERSON_NAME			DBO.UDT_NAME NULL,
													BENEFICIARY_PERSON_DATE_OF_BIRTH DBO.UDT_DATETIME NULL, 
													CALCULATION_TYPE_ID				DBO.UDT_CODE_ID NOT NULL,
													CALCULATION_TYPE_VALUE			DBO.UDT_CODE_VALUE NULL,
													BENEFIT_TYPE_ID					DBO.UDT_CODE_ID NOT NULL,
													BENEFIT_TYPE_VALUE				DBO.UDT_CODE_VALUE NULL,
													STATUS_ID						DBO.UDT_CODE_ID NOT NULL,
													STATUS_VALUE					DBO.UDT_CODE_VALUE NULL,
													RETIREMENT_DATE					DBO.UDT_DATETIME NOT NULL,
													AGE								DBO.UDT_AGE_DEC NOT NULL,
													CREATED_BY						DBO.UDT_CREATEDBY NOT NULL,
													CREATED_DATE					DBO.UDT_DATETIME NOT NULL,
													MODIFIED_BY						DBO.UDT_MODIFIEDBY NOT NULL,
													MODIFIED_DATE					DBO.UDT_DATETIME NOT NULL,
													UPDATE_SEQ						DBO.UDT_UPDSEQ NOT NULL )
													
	ALTER TABLE SGT_BENEFIT_CALCULATION_HEADER
	ADD CONSTRAINT PK_SGT_BENEFIT_CALCULATION_HEADER_BENEFIT_CALCULATION_HEADER_ID
	PRIMARY KEY CLUSTERED (BENEFIT_CALCULATION_HEADER_ID) ON [PRIMARY]
GO


-- 2.SGT_BENEFIT_CALCULATION_DETAIL
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_BENEFIT_CALCULATION_DETAIL')
BEGIN 
	PRINT 'TABLE SGT_BENEFIT_CALCULATION_DETAIL ALREADY EXISTS.'
	DROP TABLE SGT_BENEFIT_CALCULATION_DETAIL
END
	PRINT 'CREATING TABLE - SGT_BENEFIT_CALCULATION_DETAIL'
	CREATE TABLE SGT_BENEFIT_CALCULATION_DETAIL (	BENEFIT_CALCULATION_DETAIL_ID	DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
													BENEFIT_CALCULATION_HEADER_ID	DBO.UDT_ID NOT NULL,
													BENEFIT_APPLICATION_DETAIL_ID	DBO.UDT_ID NULL,
													PERSON_ACCOUNT_ID				DBO.UDT_ID NOT NULL,
													PLAN_ID							DBO.UDT_ID NOT NULL,
													VESTED_DATE						DBO.UDT_DATETIME NULL,
													BENEFIT_SUBTYPE_ID				DBO.UDT_CODE_ID NOT NULL,
													BENEFIT_SUBTYPE_VALUE			DBO.UDT_CODE_VALUE NULL,
													UNREDUCED_BENEFIT_AMOUNT		DBO.UDT_AMT NULL,
													FINAL_MONTHLY_BENEFIT_AMOUNT	DBO.UDT_AMT NULL,
													EARLY_REDUCTION_FACTOR			DBO.UDT_RATE NULL,
													EARLY_REDUCED_BENEFIT_AMOUNT	DBO.UDT_AMT NULL,
													ADDITIONAL_ACCRUED_BENEFIT_AMOUNT DBO.UDT_AMT NULL,
													ACTUARIAL_ACCRUED_BENEFIT_AMOUNT  DBO.UDT_AMT NULL,
													IAP_BALANCE_AMOUNT				DBO.UDT_AMT NULL,
													TOTAL_EE_CONTRIBUTION_AMOUNT	DBO.UDT_AMT NULL,
													TOTAL_EE_INTEREST_AMOUNT		DBO.UDT_AMT NULL,
													UVHP_BALANCE_AMOUNT				DBO.UDT_AMT NULL,
													SPECIAL_ACCOUNT_BALANCE_AMOUNT	DBO.UDT_AMT NULL,
													MINIMUM_GUARANTEE_AMOUNT		DBO.UDT_AMT NULL,
													MEMBER_EXCLUSION_AMOUNT			DBO.UDT_AMT NULL,
													STATUS_ID						DBO.UDT_CODE_ID NOT NULL,
													STATUS_VALUE					DBO.UDT_CODE_VALUE NULL,
													CREATED_BY						DBO.UDT_CREATEDBY NOT NULL,
													CREATED_DATE					DBO.UDT_DATETIME NOT NULL,
													MODIFIED_BY						DBO.UDT_MODIFIEDBY NOT NULL,
													MODIFIED_DATE					DBO.UDT_DATETIME NOT NULL,
													UPDATE_SEQ						DBO.UDT_UPDSEQ NOT NULL )

	ALTER TABLE SGT_BENEFIT_CALCULATION_DETAIL
	ADD CONSTRAINT PK_SGT_BENEFIT_CALCULATION_DETAIL_BENEFIT_CALCULATION_DETAIL_ID
	PRIMARY KEY CLUSTERED (BENEFIT_CALCULATION_DETAIL_ID) ON [PRIMARY]
GO

-- 3. SGT_BENEFIT_CALCULATION_YEARLY_DETAIL
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_BENEFIT_CALCULATION_YEARLY_DETAIL')
BEGIN 
	PRINT 'TABLE SGT_BENEFIT_CALCULATION_YEARLY_DETAIL ALREADY EXISTS.'
	DROP TABLE SGT_BENEFIT_CALCULATION_YEARLY_DETAIL
END
	PRINT 'CREATING TABLE - SGT_BENEFIT_CALCULATION_YEARLY_DETAIL'
	CREATE TABLE SGT_BENEFIT_CALCULATION_YEARLY_DETAIL (BENEFIT_CALCULATION_YEARLY_DETAIL_ID DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
														BENEFIT_CALCULATION_DETAIL_ID		DBO.UDT_ID NOT NULL,
														PLAN_YEAR							DBO.UDT_FY_YEAR NULL,
														ANNUAL_HOURS						DBO.UDT_HOURS NULL,
														QUALIFIED_YEARS_COUNT				DBO.UDT_INT NULL,
														VESTED_HOURS						DBO.UDT_HOURS NULL,
														VESTED_YEARS_COUNT					DBO.UDT_INT NULL,
														BREAK_YEARS_COUNT					DBO.UDT_INT NULL,
														HEALTH_HOURS						DBO.UDT_HOURS NULL,
														HEALTH_YEARS_COUNT					DBO.UDT_INT NULL,
														LOCAL_CREDITED_DAYS					DBO.UDT_SERVICE NULL,
														PENSION_CREDIT						DBO.UDT_SERVICE NULL,
														BENEFIT_RATE						DBO.UDT_RATE NULL,
														ACCRUED_BENEFIT_AMOUNT				DBO.UDT_AMT NULL,
														EE_CONTRIBUTION_AMOUNT				DBO.UDT_AMT NULL,
														EE_INTEREST_AMOUNT					DBO.UDT_AMT NULL,
														SUSPENDIBLE_MONTHS_COUNT			DBO.UDT_INT NULL,
														ER_DERIVED_AMOUNT					DBO.UDT_AMT NULL,
														EE_DERIVED_AMOUNT					DBO.UDT_AMT NULL,
														ACTUARIAL_ACCRUED_BENENFIT			DBO.UDT_AMT NULL,
														ACTUARIAL_EQUIVALENT_AMOUNT			DBO.UDT_AMT NULL,
														ANNUAL_ADJUSTMENT_AMOUNT			DBO.UDT_AMT NULL,
														CREATED_BY							DBO.UDT_CREATEDBY NOT NULL,
														CREATED_DATE						DBO.UDT_DATETIME NOT NULL,
														MODIFIED_BY							DBO.UDT_MODIFIEDBY NOT NULL,
														MODIFIED_DATE						DBO.UDT_DATETIME NOT NULL,
														UPDATE_SEQ							DBO.UDT_UPDSEQ NOT NULL)

	ALTER TABLE SGT_BENEFIT_CALCULATION_YEARLY_DETAIL
	ADD CONSTRAINT PK_SGT_BENEFIT_CALCULATION_YEARLY_DETAIL_BENEFIT_CALCULATION_YEARLY_DETAIL_ID
	PRIMARY KEY CLUSTERED (BENEFIT_CALCULATION_YEARLY_DETAIL_ID) ON [PRIMARY]
GO


-- 4. SGT_BENEFIT_CALCULATION_OPTIONS
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_BENEFIT_CALCULATION_OPTIONS')
BEGIN 
	PRINT 'TABLE SGT_BENEFIT_CALCULATION_OPTIONS ALREADY EXISTS.'
	DROP TABLE SGT_BENEFIT_CALCULATION_OPTIONS
END
	PRINT 'CREATING TABLE - SGT_BENEFIT_CALCULATION_OPTIONS'
	CREATE TABLE SGT_BENEFIT_CALCULATION_OPTIONS (	BENEFIT_CALCULATION_OPTION_ID		DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
													BENEFIT_CALCULATION_DETAIL_ID		DBO.UDT_ID NOT NULL,
													PLAN_BENEFIT_ID						DBO.UDT_ID NOT NULL,
													BENEFIT_OPTION_FACTOR				DBO.UDT_RATE NULL,
													BENEFIT_AMOUNT						DBO.UDT_AMT NULL,
													ACCOUNT_RELATIONSHIP_ID				DBO.UDT_CODE_ID NOT NULL,
													ACCOUNT_RELATIONSHIP_VALUE			DBO.UDT_CODE_VALUE NULL,
													SURVIVOR_RELATIONSHIP_ID			DBO.UDT_CODE_ID NOT NULL,
													SURVIVOR_RELATIONSHIP_VALUE			DBO.UDT_CODE_VALUE NULL,
													CREATED_BY							DBO.UDT_CREATEDBY NOT NULL,
													CREATED_DATE						DBO.UDT_DATETIME NOT NULL,
													MODIFIED_BY							DBO.UDT_MODIFIEDBY NOT NULL,
													MODIFIED_DATE						DBO.UDT_DATETIME NOT NULL,
													UPDATE_SEQ							DBO.UDT_UPDSEQ NOT NULL )

	ALTER TABLE SGT_BENEFIT_CALCULATION_OPTIONS
	ADD CONSTRAINT PK_SGT_BENEFIT_CALCULATION_OPTIONS_BENEFIT_CALCULATION_OPTION_ID
	PRIMARY KEY CLUSTERED (BENEFIT_CALCULATION_OPTION_ID) ON [PRIMARY]
GO


-- 5. SGT_BENEFIT_CALCULATION_DETAIL_ERROR
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_BENEFIT_CALCULATION_DETAIL_ERROR')
BEGIN 
	PRINT 'TABLE SGT_BENEFIT_CALCULATION_DETAIL_ERROR ALREADY EXISTS.'
	DROP TABLE SGT_BENEFIT_CALCULATION_DETAIL_ERROR
END
	PRINT 'CREATING TABLE - SGT_BENEFIT_CALCULATION_DETAIL_ERROR'
	CREATE TABLE SGT_BENEFIT_CALCULATION_DETAIL_ERROR (	BENEFIT_CALCULATION_DETAIL_ERROR_ID		DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
														BENEFIT_CALCULATION_DETAIL_ID			DBO.UDT_ID NOT NULL,
														MESSAGE_ID								DBO.UDT_ID NOT NULL,
														CREATED_BY								DBO.UDT_CREATEDBY NOT NULL,
														CREATED_DATE							DBO.UDT_DATETIME NOT NULL,
														MODIFIED_BY								DBO.UDT_MODIFIEDBY NOT NULL,
														MODIFIED_DATE							DBO.UDT_DATETIME NOT NULL,
														UPDATE_SEQ								DBO.UDT_UPDSEQ NOT NULL)

	ALTER TABLE SGT_BENEFIT_CALCULATION_DETAIL_ERROR
	ADD CONSTRAINT PK_SGT_BENEFIT_CALCULATION_DETAIL_ERROR_BENEFIT_CALCULATION_DETAIL_ERROR_ID
	PRIMARY KEY CLUSTERED (BENEFIT_CALCULATION_DETAIL_ERROR_ID) ON [PRIMARY]
GO


-- 6. SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR')
BEGIN 
	PRINT 'TABLE SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR ALREADY EXISTS.'
	DROP TABLE SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR
END
	PRINT 'CREATING TABLE - SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR'
	CREATE TABLE SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR(		BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR_ID		DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
																BENEFIT_PROVISION_ID							DBO.UDT_ID NOT NULL,
																BENEFIT_ACCOUNT_TYPE_ID							DBO.UDT_CODE_ID NOT NULL,
																BENEFIT_ACCOUNT_TYPE_VALUE						DBO.UDT_CODE_VALUE NULL,
																BENEFIT_ACCOUNT_SUBTYPE_ID						DBO.UDT_CODE_ID NOT NULL,
																BENEFIT_ACCOUNT_SUBTYPE_VALUE					DBO.UDT_CODE_VALUE NULL,
																AGE												DBO.UDT_AGE_DEC NULL,
																EARLY_REDUCTION_FACTOR							DBO.UDT_RATE NULL,
																CREATED_BY										DBO.UDT_CREATEDBY NOT NULL,
																CREATED_DATE									DBO.UDT_DATETIME NOT NULL,
																MODIFIED_BY										DBO.UDT_MODIFIEDBY NOT NULL,
																MODIFIED_DATE									DBO.UDT_DATETIME NOT NULL,
																UPDATE_SEQ										DBO.UDT_UPDSEQ NOT NULL)

	ALTER TABLE SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR
	ADD CONSTRAINT PK_SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR_ID
	PRIMARY KEY CLUSTERED (BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR_ID) ON [PRIMARY]
GO



---- 7. SGT_BENEFIT_PROVISION_BENEFIT_OPTION
--IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_BENEFIT_PROVISION_BENEFIT_OPTION')
--BEGIN 
--	PRINT 'TABLE SGT_BENEFIT_PROVISION_BENEFIT_OPTION ALREADY EXISTS.'
--	DROP TABLE SGT_BENEFIT_PROVISION_BENEFIT_OPTION
--END
--	PRINT 'CREATING TABLE - SGT_BENEFIT_PROVISION_BENEFIT_OPTION'
--	CREATE TABLE SGT_BENEFIT_PROVISION_BENEFIT_OPTION (	BENEFIT_PROVISION_BENEFIT_OPTION_ID DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
--														BENEFIT_PROVISION_ID				DBO.UDT_ID NOT NULL,
--														BENEFIT_ACCOUNT_ID					DBO.UDT_ID NOT NULL,
--														PLAN_BENEFIT_ID						DBO.UDT_ID NOT NULL,
--														CREATED_BY							DBO.UDT_CREATEDBY NOT NULL,
--														CREATED_DATE						DBO.UDT_DATETIME NOT NULL,
--														MODIFIED_BY							DBO.UDT_MODIFIEDBY NOT NULL,
--														MODIFIED_DATE						DBO.UDT_DATETIME NOT NULL,
--														UPDATE_SEQ							DBO.UDT_UPDSEQ NOT NULL)

--	ALTER TABLE SGT_BENEFIT_PROVISION_BENEFIT_OPTION
--	ADD CONSTRAINT PK_SGT_BENEFIT_PROVISION_BENEFIT_OPTION_BENEFIT_PROVISION_BENEFIT_OPTION_ID
--	PRIMARY KEY CLUSTERED (BENEFIT_PROVISION_BENEFIT_OPTION_ID) ON [PRIMARY]
--GO



-- 8. SGT_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR')
BEGIN 
	PRINT 'TABLE SGT_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR ALREADY EXISTS.'
	DROP TABLE SGT_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR
END
	PRINT 'CREATING TABLE - SGT_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR'
	CREATE TABLE SGT_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR (	BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR_ID	DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
																BENEFIT_PROVISION_ID						DBO.UDT_ID NOT NULL,
																BENEFIT_ACCOUNT_TYPE_ID						DBO.UDT_CODE_ID NOT NULL,
																BENEFIT_ACCOUNT_TYPE_VALUE					DBO.UDT_CODE_VALUE NULL,
																PLAN_BENEFIT_ID								DBO.UDT_ID NULL,
																PARTICIPANT_AGE								DBO.UDT_AGE_DEC NULL,
																SPOUSE_AGE									DBO.UDT_AGE_DEC NULL,
																BENEFIT_OPTION_FACTOR						DBO.UDT_RATE NULL,
																CREATED_BY									DBO.UDT_CREATEDBY NOT NULL,
																CREATED_DATE								DBO.UDT_DATETIME NOT NULL,
																MODIFIED_BY									DBO.UDT_MODIFIEDBY NOT NULL,
																MODIFIED_DATE								DBO.UDT_DATETIME NOT NULL,
																UPDATE_SEQ									DBO.UDT_UPDSEQ NOT NULL)

	ALTER TABLE SGT_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR
	ADD CONSTRAINT PK_SGT_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR_BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR_ID
	PRIMARY KEY CLUSTERED (BENEFIT_PROVISION_BENEFIT_OPTION_FACTOR_ID) ON [PRIMARY]
GO



-- 9. SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION')
BEGIN 
	PRINT 'TABLE SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION ALREADY EXISTS.'
	DROP TABLE SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION
END
	PRINT 'CREATING TABLE - SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION'
	CREATE TABLE SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION (	PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION_ID	DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
																PERSON_ACCOUNT_ID							DBO.UDT_ID NOT NULL,
																TRANSACTION_DATE							DBO.UDT_DATETIME NOT NULL,
																EFFECTIVE_DATE								DBO.UDT_DATETIME NULL,
																COMPUTATIONAL_YEAR							DBO.UDT_FY_YEAR NOT NULL,
																IAP_BALANCE_AMOUNT							DBO.UDT_AMT NULL,
																SPECIAL_ACCOUNT_BALANCE_AMOUNT				DBO.UDT_AMT NULL,
																TRANSACTION_TYPE_ID							DBO.UDT_CODE_ID NOT NULL,
																TRANSACTION_TYPE_VALUE						DBO.UDT_CODE_VALUE NULL,
																EE_CONTRIBUTION_AMOUNT						DBO.UDT_AMT NULL,
																UVHP_AMOUNT									DBO.UDT_AMT NULL,
																EE_INT_AMOUNT								DBO.UDT_AMT NULL,
																UVHP_INT_AMOUNT								DBO.UDT_AMT NULL,
																LOCAL_FROZEN_BENEFIT_AMOUNT					DBO.UDT_AMT NULL,
																CREATED_BY									DBO.UDT_CREATEDBY NOT NULL,
																CREATED_DATE								DBO.UDT_DATETIME NOT NULL,
																MODIFIED_BY									DBO.UDT_MODIFIEDBY NOT NULL,
																MODIFIED_DATE								DBO.UDT_DATETIME NOT NULL,
																UPDATE_SEQ									DBO.UDT_UPDSEQ NOT NULL)

	ALTER TABLE SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION
	ADD CONSTRAINT PK_SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION_ID
	PRIMARY KEY CLUSTERED (PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION_ID) ON [PRIMARY]
GO


-- 10. SGT_PLAN_BENEFIT_RATE
IF EXISTS (SELECT * FROM SYSOBJECTS SO WHERE SO.NAME LIKE 'SGT_PLAN_BENEFIT_RATE')
BEGIN 
	PRINT 'TABLE SGT_PLAN_BENEFIT_RATE ALREADY EXISTS.'
	DROP TABLE SGT_PLAN_BENEFIT_RATE
END
	PRINT 'CREATING TABLE - SGT_PLAN_BENEFIT_RATE'
	CREATE TABLE SGT_PLAN_BENEFIT_RATE (PLAN_BENEFIT_RATE_ID	DBO.UDT_IDENTITY IDENTITY(1,1) NOT NULL,
										PLAN_BENEFIT_ID			DBO.UDT_ID NULL,
										RATE_TYPE_ID			DBO.UDT_CODE_ID NOT NULL,
										RATE_TYPE_VALUE			DBO.UDT_CODE_VALUE NULL,
										QUALIFIED_YEAR_LIMIT_ID DBO.UDT_CODE_ID NOT NULL,
										QUALIFIED_YEAR_LIMIT_VALUE DBO.UDT_CODE_VALUE NULL,
										EFFECTIVE_DATE			DBO.UDT_DATETIME NOT NULL,
										PLAN_YEAR				DBO.UDT_FY_YEAR NOT NULL,
										BREAK_IN_SERVICE_YEAR	DBO.UDT_FY_YEAR NULL,
										RATE					DBO.UDT_RATE NULL,
										INCREASE_PERCENTAGE		DBO.UDT_PERC NULL,
										INCREASE_FACTOR			DBO.UDT_RATE NULL,
										CREATED_BY				DBO.UDT_CREATEDBY NOT NULL,
										CREATED_DATE			DBO.UDT_DATETIME NOT NULL,
										MODIFIED_BY				DBO.UDT_MODIFIEDBY NOT NULL,
										MODIFIED_DATE			DBO.UDT_DATETIME NOT NULL,
										UPDATE_SEQ				DBO.UDT_UPDSEQ NOT NULL)

	ALTER TABLE SGT_PLAN_BENEFIT_RATE
	ADD CONSTRAINT PK_SGT_PLAN_BENEFIT_RATE_PLAN_BENEFIT_RATE_ID
	PRIMARY KEY CLUSTERED (PLAN_BENEFIT_RATE_ID) ON [PRIMARY]
GO


---------------- INSERT CODE VALUES FOR CALCULATIONS ----------------




-- 1. CALCULATION TYPES
INSERT INTO SGS_CODE (CODE_ID,DESCRIPTION,DATA1_CAPTION,DATA1_TYPE,DATA2_CAPTION,DATA2_TYPE,DATA3_CAPTION,
DATA3_TYPE,FIRST_LOOKUP_ITEM,FIRST_MAINTENANCE_ITEM,COMMENTS,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2001, 'Calculation Type', NULL, NULL, NULL, NULL, NULL, NULL, 'All', NULL, 'Different Calculation Types', NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)


INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,
LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2001, 'ESTI', 'Estimate Calculation', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,
LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2001, 'FINL', 'Final Calculation', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)


-- 2. CALCULATION STATUSES
INSERT INTO SGS_CODE (CODE_ID,DESCRIPTION,DATA1_CAPTION,DATA1_TYPE,DATA2_CAPTION,DATA2_TYPE,DATA3_CAPTION,
DATA3_TYPE,FIRST_LOOKUP_ITEM,FIRST_MAINTENANCE_ITEM,COMMENTS,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2002, 'Calculation Status', NULL, NULL, NULL, NULL, NULL, NULL, 'All', NULL, 'Different Calculation Statuses', NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)


INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,
LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2002, 'PEND', 'Pending Calculation', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,
LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2002, 'APPR', 'Approved Calculation', NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,
LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2002, 'CANC', 'Cancelled Calculation', NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)


-- 3. ACCOUNT RELATIONSHIPS
INSERT INTO SGS_CODE (CODE_ID,DESCRIPTION,DATA1_CAPTION,DATA1_TYPE,DATA2_CAPTION,DATA2_TYPE,DATA3_CAPTION,
DATA3_TYPE,FIRST_LOOKUP_ITEM,FIRST_MAINTENANCE_ITEM,COMMENTS,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2003, 'Account Relationships', NULL, NULL, NULL, NULL, NULL, NULL, 'All', NULL, 'Different Account Relationships', NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,
LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2003, 'MEMB', 'Member Account', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,
LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2003, 'BENE', 'Beneficiary Account', NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)



-- 4. BENEFIT ACCOUNT TYPES (1502)
--INSERT INTO SGS_CODE (CODE_ID,DESCRIPTION,DATA1_CAPTION,DATA1_TYPE,DATA2_CAPTION,DATA2_TYPE,DATA3_CAPTION,
--DATA3_TYPE,FIRST_LOOKUP_ITEM,FIRST_MAINTENANCE_ITEM,COMMENTS,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
--VALUES (1502, 'Benefit Account Types', NULL, NULL, NULL, NULL, NULL, NULL, 'All', NULL, 'Different Benefit Account Types', NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)


-- 5. BENEFIT ACCOUNT SUBTYPES (1501)
--INSERT INTO SGS_CODE (CODE_ID,DESCRIPTION,DATA1_CAPTION,DATA1_TYPE,DATA2_CAPTION,DATA2_TYPE,DATA3_CAPTION,
--DATA3_TYPE,FIRST_LOOKUP_ITEM,FIRST_MAINTENANCE_ITEM,COMMENTS,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
--VALUES (1501, 'Benefit Account Subtypes', NULL, NULL, NULL, NULL, NULL, NULL, 'All', NULL, 'Different Benefit Account Subtypes', NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)


-- 6. RATE TYPES
INSERT INTO SGS_CODE (CODE_ID,DESCRIPTION,DATA1_CAPTION,DATA1_TYPE,DATA2_CAPTION,DATA2_TYPE,DATA3_CAPTION,
DATA3_TYPE,FIRST_LOOKUP_ITEM,FIRST_MAINTENANCE_ITEM,COMMENTS,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES (2006, 'Rate Types', NULL, NULL, NULL, NULL, NULL, NULL, 'All', NULL, 'Different Rate Types', NULL, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)




-- Puneet Punjabi 02/22/2012
-- New Stored Procedure for Pension Calculation

USE [OPUS]
GO

/****** Object:  StoredProcedure [dbo].[usp_GetWorkDataForPlanYear]    Script Date: 02/22/2012 13:09:49 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[usp_GetWorkDataForPlanYear]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[usp_GetWorkDataForPlanYear]
GO

USE [OPUS]
GO

/****** Object:  StoredProcedure [dbo].[usp_GetWorkDataForPlanYear]    Script Date: 02/22/2012 13:09:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[usp_GetWorkDataForPlanYear](@SSN char(10),@PLANYEAR int)
AS
BEGIN
SET NOCOUNT ON
DECLARE @PensionWorkHistory TABLE(
	[ReportID] [varchar](18) NULL,
	[EmpAccountNo] [int] NULL,
	[ComputationYear] [smallint] NULL,
	[FromDate] [smalldatetime] NULL,
	[ToDate] [smalldatetime] NULL,
	[Weeks] [char](2) NULL,
	[Received] [smalldatetime] NULL,
	[Processed] [smalldatetime] NULL,
	[HoursID] [varchar](24) NULL,
	[SSN] [char](9) NULL,
	[LastName] [varchar](50) NULL,
	[FirstName] [varchar](50) NULL,
	[UnionCode] [int] NULL,
	[PensionPlan] [smallint] NULL,
	[PensionCredit] [numeric](7, 3) NULL,
	[L52VestedCredit] [smallint] NULL,
	[PensionHours] [numeric](7, 1) NULL,
	[IAPHours] [numeric](7, 1) NULL,
	[IAPHoursA2] [numeric](7, 1) NULL,
	[IAPPercent] [money] NULL,
	[ActiveHealthHours] [numeric](7, 1) NULL,
	[RetireeHealthHours] [numeric](7, 1) NULL,
	[MPI_PERSON_ID] [varchar](15) NULL,
	[RateGroup] [varchar](4) NULL,
	[HoursStatus] [int] NULL,
	[LateMonthly] [varchar](1)  NULL,
	[LateAnnual] [varchar](1)  NULL,
	[UnionMisc] [char](2) NULL,
	[HoursWorked] [numeric](7, 1) NULL,
	[IAPHourlyRate] [money] NULL,
	[Source] [varchar](4) NOT NULL,
	[ToHealthSystem] [int] NULL,
	[ToPensionSystem] [int] NULL,
	[IsActiveHealth] [int] NULL,
	[IsRetireeHealth] [int] NULL,
	[IsPension] [int] NULL,
	[IsIAPHourly] [int] NULL
) 

INSERT INTO @PensionWorkHistory 
EXEC usp_PensionInterface4OPUS @SSN

SELECT DISTINCT ComputationYear, FromDate, PensionHours
FROM @PensionWorkHistory AS VPIO 
where VPIO.SSN=@SSN AND VPIO.ComputationYear = @PLANYEAR

END

GO


-------------- INSERT THE EARLY RETIREMENT FACTORS FOR THE PENSION PLAN
-- REDUCED EARLY RETIREMENT FACTORS
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 55, 0.49, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 56, 0.52, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 57, 0.555, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 58, 0.595, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 59, 0.64, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 60, 0.69, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 61, 0.745, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 62, 0.80, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 63, 0.86, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 64, 0.925, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'REDE', 65, 1.00, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)



-- SPECIAL REDUCED EARLY RETIREMENT FACTORS
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 55, 0.71, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 56, 0.754, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 57, 0.804, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 58, 0.862, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 59, 0.928, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 60, 1.00, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 61, 1.00, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 62, 1.00, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 63, 1.00, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 64, 1.00, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)

INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE_FACTOR (	BENEFIT_PROVISION_ID, BENEFIT_ACCOUNT_TYPE_ID, BENEFIT_ACCOUNT_TYPE_VALUE, BENEFIT_ACCOUNT_SUBTYPE_ID, BENEFIT_ACCOUNT_SUBTYPE_VALUE,
															AGE, EARLY_REDUCTION_FACTOR, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2, 1502, 'RTMT', 1501, 'SPLR', 65, 1.00, 'ppunjabi', GETDATE(), 'ppunjabi', GETDATE(), 0)


-----ABHISHEK CHANGES FOR TABLES WE HAD CREATED IN CALCULATION L----------------
-----THESE TABLES COULD BE MERGED IN THE ONE FACTOR TABLE BCLL STILL CHECKIN THE SCRIPT -------------

/****** Object:  Table [dbo].[SGT_BENEFIT_FACTOR_LOCAL]    Script Date: 03/02/2012 19:32:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGT_BENEFIT_FACTOR_LOCAL](
	[BENEFIT_FACTOR_LOCAL_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[PLAN_ID] [int] NULL,
	[BENEFIT_OPTION_ID] [int] NULL,
	[BENEFIT_OPTION_VALUE] [varchar](4) NULL,
	[PARTICIPANT_AGE] [numeric](18, 2) NULL,
	[SPOUSE_AGE] [numeric](18, 2) NULL,
	[FACTOR] [numeric](18, 5) NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NULL,
PRIMARY KEY CLUSTERED 
(
	[BENEFIT_FACTOR_LOCAL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



/****** Object:  Table [dbo].[SGT_BENEFIT_PROVISION_LUMPSUM_FACTOR]    Script Date: 03/02/2012 19:32:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGT_BENEFIT_PROVISION_LUMPSUM_FACTOR](
	[BENEFIT_FACTOR_LUMPSUM_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[PARTICIPANT_AGE] [numeric](18, 2) NULL,
	[YEAR] [dbo].[UDT_INT] NULL,
	[DEFERRED_FACTOR] [numeric](18, 5) NULL,
	[LIFE_FACTOR] [numeric](18, 5) NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NULL,
PRIMARY KEY CLUSTERED 
(
	[BENEFIT_FACTOR_LUMPSUM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



