
----------------------------------------------------------------------------------------------------------------------------------
-- Name - Rashmi Sheri
-- Date - 12/14/2011
-- Purpose - Added message_id- 5145,5146 in to the SGS_MESSAGES table.
----------------------------------------------------------------------------------------------------------------------------------

declare @currentdatetime datetime
set @currentdatetime = getdate()
IF EXISTS (SELECT MESSAGE_ID FROM SGS_MESSAGES WHERE MESSAGE_ID = 5145)
PRINT 'MESSAGE_ID = 5145 already exits in SGS_MESSAGES tables'
ELSE
INSERT into dbo.SGS_MESSAGES (MESSAGE_ID, DISPLAY_MESSAGE, SEVERITY_ID, SEVERITY_VALUE, INTERNAL_INSTRUCTIONS, EMPLOYER_INSTRUCTIONS, RESPONSIBILITY_ID, RESPONSIBILITY_VALUE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ) 
VALUES (5145, 'Date of death exists for this participant.Disability Application cannot be created.', 16 , 'E', Null, Null, 16, null, 'rashmi.sheri', @currentdatetime, 'rashmi.sheri', @currentdatetime, 0)
GO

declare @currentdatetime datetime
set @currentdatetime = getdate()
IF EXISTS (SELECT MESSAGE_ID FROM SGS_MESSAGES WHERE MESSAGE_ID = 5146)
PRINT 'MESSAGE_ID = 5146 already exits in SGS_MESSAGES tables'
ELSE
INSERT into dbo.SGS_MESSAGES (MESSAGE_ID, DISPLAY_MESSAGE, SEVERITY_ID, SEVERITY_VALUE, INTERNAL_INSTRUCTIONS, EMPLOYER_INSTRUCTIONS, RESPONSIBILITY_ID, RESPONSIBILITY_VALUE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ) 
VALUES (5146, 'Date of death exists for this participant.Retirement Application cannot be created.', 16 , 'E', Null, Null, 16, null, 'rashmi.sheri', @currentdatetime, 'rashmi.sheri', @currentdatetime, 0)
GO

----------------------------------------------------------------------------------------------------------------------------------
-- Name - Kunal
-- Date - 12/14/2011
-- Purpose - add file id for death report,corresponding batch
----------------------------------------------------------------------------------------------------------------------------------
INSERT dbo.SGS_FILE ([FILE_ID],[DESCRIPTION],[DELIMITED_BY],[TRANSACTION_CODE_POS],[TRANSACTION_CODE_LENGTH],[TRANSACTION_CODE_VALUE],[HEADER_GROUP_POS],[HEADER_GROUP_LENGTH],[XML_LAYOUT_FILE],[INBOUND_MASK],[MAILBOX_PATH_CODE],[STAGING_PATH_CODE],[ERROR_PATH_CODE],[PROCESS_PATH_CODE],[FILE_STATUS_ID],[FILE_STATUS_VALUE],[INBOUND_OUTBOUND_FLAG],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ],[EMAIL_NOTIFICATION],[OTHER_PARAMETERS],[GROUP_PROCESS_FLAG])VALUES(1,'Death Report',',',NULL,NULL,'None',NULL,NULL,'fleDeathReportOut','*.*','DeaRep','DeaStag','DeaErr','DeaPrcss',26,'A','O','kunal.arora','Dec  8 2011  5:02:13:053PM','kunal.arora','Dec 12 2011  1:03:33:317PM',5,NULL,NULL,'N')

SET IDENTITY_INSERT [dbo].[SGS_JOB_SCHEDULE] ON
GO
INSERT dbo.SGS_JOB_SCHEDULE ([JOB_SCHEDULE_ID],[SCHEDULE_NAME],[ACTIVE_FLAG],[FREQUENCY_TYPE_ID],[FREQUENCY_TYPE_VALUE],[FREQUENCY_INTERVAL],[FREQ_SUBDAY_TYPE],[FREQ_SUBDAY_INTERVAL],[FREQ_RELATIVE_INTERVAL],[FREQ_RECURANCE_FACTOR],[START_DATE],[END_DATE],[START_TIME],[END_TIME],[STATUS_ID],[STATUS_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ],[PRIORITY_ID],[PRIORITY_VALUE],[CANCEL_PROCEDURE_NOTES],[RESTART_PROCEDURE_NOTES],[BATCH_STATUS_EMAIL_RECIPIENT_GROUPS],[BATCH_ERROR_EMAIL_RECIPIENT_GROUPS],[EXECUTE_ON_ORG_HOLIDAY_FLAG],[SCHEDULE_CODE],[CANCELLABLE_JOB_FLAG])VALUES(14,'Death Monthly Report','Y',6017,'16',1,1,NULL,1,1,'Dec 13 2011 12:00:00:000AM',NULL,NULL,NULL,6020,'VALD','kunal.arora','Dec 13 2011  7:17:45:633PM','kunal.arora','Dec 13 2011  7:22:14:503PM',3,6019,'P3',NULL,NULL,NULL,NULL,'N',NULL,'N')
GO
SET IDENTITY_INSERT [dbo].[SGS_JOB_SCHEDULE] OFF
GO

SET IDENTITY_INSERT [dbo].[SGS_BATCH_SCHEDULE] ON
GO
INSERT dbo.SGS_BATCH_SCHEDULE ([BATCH_SCHEDULE_ID],[STEP_NO],[STEP_NAME],[STEP_DESCRIPTION],[FREQUENCY_IN_DAYS],[FREQUENCY_IN_MONTHS],[NEXT_RUN_DATE],[STEP_PARAMETERS],[ACTIVE_FLAG],[REQUIRES_TRANSACTION_FLAG],[EMAIL_NOTIFICATION],[ORDER_NO],[CUTOFF_START],[CUTOFF_END],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(4,4,'Deatg Report Batch','Death Report Batch',NULL,NULL,NULL,NULL,'Y','N',NULL,NULL,NULL,NULL,'kunal.arora','Dec 13 2011  7:24:08:090PM','kunal.arora','Dec 13 2011  7:24:08:090PM',0)
GO
SET IDENTITY_INSERT [dbo].[SGS_BATCH_SCHEDULE] OFF
GO

INSERT dbo.SGS_JOB_SCHEDULE_DETAIL ([JOB_SCHEDULE_ID],[STEP_NO],[STATUS_ID],[STATUS_VALUE],[ORDER_NUMBER],[DEPENDENT_STEP_NO],[DEPENDENT_STEP_RETURN_VALUE],[OPERATOR_ID],[OPERATOR_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(14,4,6018,'VALD',1,NULL,NULL,6021,NULL,'kunal.arora','Dec 13 2011  7:22:14:457PM','kunal.arora','Dec 13 2011  7:22:14:487PM',1)


SET IDENTITY_INSERT [dbo].[SGS_SYSTEM_PATHS] ON
GO
INSERT dbo.SGS_SYSTEM_PATHS ([PATH_ID],[PATH_CODE],[PATH_VALUE],[PATH_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(5,'DeaRep','Death\Report\','Death report directory','kunal.arora','Dec  8 2011  4:10:51:993PM','kunal.arora','Dec  8 2011  4:10:51:993PM',0)
INSERT dbo.SGS_SYSTEM_PATHS ([PATH_ID],[PATH_CODE],[PATH_VALUE],[PATH_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(6,'DeaErr','Death\Error\','Error in Death Report','kunal.arora','Dec 12 2011 12:58:17:347PM','kunal.arora','Dec 12 2011 12:58:17:347PM',0)
INSERT dbo.SGS_SYSTEM_PATHS ([PATH_ID],[PATH_CODE],[PATH_VALUE],[PATH_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(7,'DeaPrcss','Death\Processed\','Death Processed','kunal.arora','Dec 12 2011  1:01:19:630PM','kunal.arora','Dec 12 2011  1:01:19:630PM',0)
INSERT dbo.SGS_SYSTEM_PATHS ([PATH_ID],[PATH_CODE],[PATH_VALUE],[PATH_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(8,'DeaStag','Death\Staging\','Staging','kunal.arora','Dec 12 2011  1:03:57:880PM','kunal.arora','Dec 12 2011  1:03:57:880PM',0)
GO
SET IDENTITY_INSERT [dbo].[SGS_SYSTEM_PATHS] OFF
GO