----------------------------------------------------------------------------------------------------------------------------------
-- Name - Kunal Arora
-- Date - 12/14/2011
-- Purpose - Create File Tables
----------------------------------------------------------------------------------------------------------------------------------
drop table SGS_FILE

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_FILE](
	[FILE_ID] [dbo].[UDT_IDENTITY] NOT NULL,
	[DESCRIPTION] [dbo].[UDT_DESC] NULL,
	[DELIMITED_BY] [dbo].[UDT_IND] NULL,
	[TRANSACTION_CODE_POS] [dbo].[UDT_INT] NULL,
	[TRANSACTION_CODE_LENGTH] [dbo].[UDT_INT] NULL,
	[TRANSACTION_CODE_VALUE] [dbo].[UDT_LONGDESC] NULL,
	[HEADER_GROUP_POS] [dbo].[UDT_INT] NULL,
	[HEADER_GROUP_LENGTH] [dbo].[UDT_INT] NULL,
	[XML_LAYOUT_FILE] [dbo].[UDT_FILE_NAME] NULL,
	[INBOUND_MASK] [dbo].[UDT_DATA] NULL,
	[MAILBOX_PATH_CODE] [dbo].[UDT_DATA] NULL,
	[STAGING_PATH_CODE] [dbo].[UDT_DATA] NULL,
	[ERROR_PATH_CODE] [dbo].[UDT_DATA] NULL,
	[PROCESS_PATH_CODE] [dbo].[UDT_DATA] NULL,
	[FILE_STATUS_ID] [dbo].[UDT_CODE_ID] NOT NULL,
	[FILE_STATUS_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
	[INBOUND_OUTBOUND_FLAG] [dbo].[UDT_FLAG] NOT NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
	[EMAIL_NOTIFICATION] [dbo].[UDT_NOTES] NULL,
	[OTHER_PARAMETERS] [dbo].[UDT_DESC] NULL,
	[GROUP_PROCESS_FLAG] [dbo].[UDT_FLAG] NOT NULL,
 CONSTRAINT [PK_SGS_FILE_FILE_ID] PRIMARY KEY CLUSTERED 
(
	[FILE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SGS_FILE] ADD  CONSTRAINT [DF_SGS_FILE_FILE_STATUS_ID]  DEFAULT ((26)) FOR [FILE_STATUS_ID]
GO


drop table SGS_FILE_HDR

/****** Object:  Table [dbo].[SGS_FILE_HDR]    Script Date: 12/14/2011 16:55:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_FILE_HDR](
	[FILE_HDR_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[MAILBOX_FILE_NAME] [dbo].[UDT_FILE_LOCATION] NULL,
	[PROCESSED_FILE_NAME] [dbo].[UDT_FILE_LOCATION] NULL,
	[PROCESSED_DATE] [dbo].[UDT_DATE] NULL,
	[FILE_ID] [dbo].[UDT_ID] NOT NULL,
	[REFERENCE_ID] [dbo].[UDT_ID] NULL,
	[STATUS_ID] [dbo].[UDT_CODE_ID] NOT NULL,
	[STATUS_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
	[NO_OF_ROWS] [dbo].[UDT_INT] NULL,
	[CYCLE_NO] [dbo].[UDT_INT] NULL,
	[COMMENTS] [dbo].[UDT_NOTES] NULL,
	[ERROR_MESSAGE] [dbo].[UDT_COMMENTS] NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK_SGS_FILE_HDR_FILE_HDR_ID] PRIMARY KEY CLUSTERED 
(
	[FILE_HDR_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


drop table SGS_FILE_DTL

/****** Object:  Table [dbo].[SGS_FILE_DTL]    Script Date: 12/14/2011 16:56:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_FILE_DTL](
	[FILE_DTL_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[FILE_HDR_ID] [dbo].[UDT_ID] NOT NULL,
	[TRANSACTION_CODE_VALUE] [dbo].[UDT_DATA50] NULL,
	[HEADER_GROUP_VALUE] [dbo].[UDT_DATA] NULL,
	[LINE_NO] [dbo].[UDT_INT] NULL,
	[RECORD_DATA] [dbo].[UDT_FILE_MAX] NULL,
	[STATUS_ID] [dbo].[UDT_CODE_ID] NOT NULL,
	[STATUS_VALUE] [dbo].[UDT_CODE_VALUE] NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK_SGS_FILE_DTL] PRIMARY KEY CLUSTERED 
(
	[FILE_DTL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


