CREATE UNIQUE CLUSTERED INDEX [CIX_ServiceDeploymentsTable]
    ON [System.Activities.DurableInstancing].[ServiceDeploymentsTable]([Id] ASC) WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

