CREATE NONCLUSTERED INDEX [NCIX_KeysTable_SurrogateInstanceId]
    ON [System.Activities.DurableInstancing].[KeysTable]([SurrogateInstanceId] ASC) WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

