-- =============================================
-- Script Template
-- =============================================
-------------------------------------
--Make sure to add do & xml along.
--------------------------------------
IF NOT EXISTS (	SELECT SO.ID FROM SYSOBJECTS SO INNER JOIN SYSCOLUMNS SC ON SO.id = SC.id 
WHERE SO.name = 'SGT_BENEFIT_CALCULATION_HEADER' AND SC.name = 'MSS_FLAG')
BEGIN
PRINT  'ADDING COLUMN MSS_FLAG IN TABLE SGT_BENEFIT_CALCULATION_HEADER'
ALTER TABLE SGT_BENEFIT_CALCULATION_HEADER
ADD MSS_FLAG UDT_FLAG NULL
END
GO

IF NOT EXISTS (	SELECT SO.ID FROM SYSOBJECTS SO INNER JOIN SYSCOLUMNS SC ON SO.id = SC.id 
WHERE SO.name = 'SGT_QDRO_CALCULATION_HEADER' AND SC.name = 'MSS_FLAG')
BEGIN
PRINT  'ADDING COLUMN MSS_FLAG IN TABLE SGT_QDRO_CALCULATION_HEADER'
ALTER TABLE SGT_QDRO_CALCULATION_HEADER
ADD MSS_FLAG UDT_FLAG NULL
END
GO
----Workflow activity : make sure do cdo os updated
IF NOT EXISTS (	SELECT SO.ID FROM SYSOBJECTS SO INNER JOIN SYSCOLUMNS SC ON SO.id = SC.id 
WHERE SO.name = 'SGW_ACTIVITY' AND SC.name = 'MSS_DISPLAY_MESSAGE')
BEGIN
PRINT  'ADDING COLUMN MSS_DISPLAY_MESSAGE IN TABLE SGW_ACTIVITY'
ALTER TABLE SGW_ACTIVITY
ADD MSS_DISPLAY_MESSAGE UDT_LONGNAME NULL
END
GO

IF NOT EXISTS (	SELECT SO.ID FROM SYSOBJECTS SO INNER JOIN SYSCOLUMNS SC ON SO.id = SC.id 
WHERE SO.name = 'SGW_ACTIVITY' AND SC.name = 'PLAN_ID')
BEGIN
PRINT  'ADDING COLUMN PLAN_ID IN TABLE SGW_ACTIVITY'
ALTER TABLE SGW_ACTIVITY
ADD PLAN_ID UDT_ID NULL
END
GO

---to store pdf docs
IF NOT EXISTS (SELECT [PATH_ID] FROM SGS_SYSTEM_PATHS WHERE [PATH_CODE] = 'MSS')
INSERT dbo.SGS_SYSTEM_PATHS ([PATH_CODE],[PATH_VALUE],[PATH_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
VALUES('MSS','MSS\Documents\','PDF Documents.','kunal.arora',GETDATE(),'kunal.arora',GETDATE(),0)
ELSE
PRINT 'Already Exist in Table SGS_SYSTEM_PATH'
GO

update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE = 'Retirement Application Approval.',PLAN_ID=NULL where ACTIVITY_ID=14
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Pension Retirement Calculation Approval',PLAN_ID=2 where ACTIVITY_ID=16
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='IAP Retirement Calculation Approval',PLAN_ID=1 where ACTIVITY_ID=18
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 Retirement Calculation Approval. ',PLAN_ID=7 where ACTIVITY_ID=19
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 700 Retirement Calculation Approval',PLAN_ID=6 where ACTIVITY_ID=20
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 Retirement Calculation Approval',PLAN_ID=8 where ACTIVITY_ID=21
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 600 Retirement Calculation Approval',PLAN_ID=3 where ACTIVITY_ID=22
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 666 Retirement Calculation Approval',PLAN_ID=4 where ACTIVITY_ID=23
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Withdrawal Application Approval',PLAN_ID=NULL where ACTIVITY_ID=26
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Non-Vested-EE/UVHP Withdrawal Calculation Approval',PLAN_ID=2 where ACTIVITY_ID=28
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='IAP Withdrawal Calculation Approval',PLAN_ID=1 where ACTIVITY_ID=29
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Disability Application Approval',PLAN_ID=NULL where ACTIVITY_ID=43
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 Disability Calculation Approval',PLAN_ID=7 where ACTIVITY_ID=45
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 700 Disability Calculation Approval',PLAN_ID=6 where ACTIVITY_ID=46
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 600 Disability Calculation Approval',PLAN_ID=3 where ACTIVITY_ID=48
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 666 Disability Calculation Approval',PLAN_ID=4 where ACTIVITY_ID=49
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Pension Disability Calculation Approval',PLAN_ID=2 where ACTIVITY_ID=50
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='IAP Disability Calculation Approval',PLAN_ID=1 where ACTIVITY_ID=51
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='QDRO Application Approval',PLAN_ID=NULL where ACTIVITY_ID=55
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 QDRO Calculation Approval',PLAN_ID=7 where ACTIVITY_ID=59
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 700 QDRO Calculation Approval',PLAN_ID=6 where ACTIVITY_ID=60
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 600 QDRO Calculation Approval',PLAN_ID=3 where ACTIVITY_ID=62
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 666 QDRO Calculation Approval',PLAN_ID=4 where ACTIVITY_ID=63
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Pension QDRO Calculation Approval',PLAN_ID=2 where ACTIVITY_ID=64
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='IAP QDRO Calculation Approval',PLAN_ID=1 where ACTIVITY_ID=65
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 Pension Payment Setup',PLAN_ID=7 where ACTIVITY_ID=67
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 700 Pension Payment Setup',PLAN_ID=6 where ACTIVITY_ID=69
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 Pension Payment Setup',PLAN_ID=8 where ACTIVITY_ID=71
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 600 Pension Payment Setup',PLAN_ID=3 where ACTIVITY_ID=73
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 666 Pension Payment Setup',PLAN_ID=4 where ACTIVITY_ID=75
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Pension Payment Setup',PLAN_ID=2 where ACTIVITY_ID=77
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='IAP Payment Setup',PLAN_ID=1 where ACTIVITY_ID=79
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 Disability Payment Setup ',PLAN_ID=7 where ACTIVITY_ID=103
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 700 Disability Payment Setup',PLAN_ID=6 where ACTIVITY_ID=104
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 Disability Calculation Approval',PLAN_ID=8 where ACTIVITY_ID=106
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 Payment Setup',PLAN_ID=8 where ACTIVITY_ID=108
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 600 Payment Setup',PLAN_ID=3 where ACTIVITY_ID=110
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 666 Payment Setup',PLAN_ID=4 where ACTIVITY_ID=112
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Pension Payment Setup',PLAN_ID=2 where ACTIVITY_ID=114
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='IAP Payment Setup',PLAN_ID=1 where ACTIVITY_ID=116
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Disability Application Approval',PLAN_ID=NULL where ACTIVITY_ID=119
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 Disability Calculation Approval',PLAN_ID=7 where ACTIVITY_ID=121
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 Disability Payment Setup',PLAN_ID=7 where ACTIVITY_ID=123
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 700 Disability Calculation Approval',PLAN_ID=6 where ACTIVITY_ID=124
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 700 Disability Payment Setup',PLAN_ID=6 where ACTIVITY_ID=126
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 Disability Calculation Approval',PLAN_ID=8 where ACTIVITY_ID=127
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 Disability Payment Setup',PLAN_ID=8 where ACTIVITY_ID=129
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 600 Disability Calculation Approval',PLAN_ID=3 where ACTIVITY_ID=130
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 600 Disability Payment Setup',PLAN_ID=3 where ACTIVITY_ID=132
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 666 Disability Calculation Approval',PLAN_ID=4 where ACTIVITY_ID=133
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 666 Disability Payment Setup',PLAN_ID=4 where ACTIVITY_ID=135
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Pension Disability Calculation Approval',PLAN_ID=2 where ACTIVITY_ID=136
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Pension Disability Payment Setup',PLAN_ID=2 where ACTIVITY_ID=138
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Non-Vested-EE/UVHP Withdrawal Payment Setup',PLAN_ID=2 where ACTIVITY_ID=151
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='IAP Withdrawal Payment Setup',PLAN_ID=1 where ACTIVITY_ID=152
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 Special Account Withdrawal Payment Setup',PLAN_ID=7 where ACTIVITY_ID=153
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 Special Account Withdrawal Payment Setup',PLAN_ID=8 where ACTIVITY_ID=154
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 52 Qdro Payment Setup',PLAN_ID=7 where ACTIVITY_ID=163
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 700 Qdro Payment Setup',PLAN_ID=6 where ACTIVITY_ID=165
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 Qdro Payment Setup',PLAN_ID=8 where ACTIVITY_ID=168
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 600 Qdro Payment Setup',PLAN_ID=3 where ACTIVITY_ID=170
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 666 Qdro Payment Setup',PLAN_ID=4 where ACTIVITY_ID=172
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Pension Qdro Payment Setup',PLAN_ID=2 where ACTIVITY_ID=174
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='IAP QDRO Payment Setup',PLAN_ID=1 where ACTIVITY_ID=176
update SGW_ACTIVITY SET MSS_DISPLAY_MESSAGE ='Local 161 QDRO Calculation Approval',PLAN_ID=8 where ACTIVITY_ID=177

IF NOT EXISTS (SELECT * FROM SGS_CODE_VALUE WHERE CODE_ID = 52 and CODE_VALUE = 'MSSA')
BEGIN
INSERT INTO SGS_CODE_VALUE
VALUES(52,'MSSA','MSS Application','MSS',null,null,null,GETDATE(),null,1,null,'kunal.arora',GETDATE(),'kunal.arora',GETDATE(),0)
END

----Done On Sys Till 9th Sept---
---7th Oct to pick forms from mpi link
IF NOT EXISTS (SELECT * FROM SGS_CODE_VALUE WHERE CODE_ID = 52 and CODE_VALUE = 'MSER')
BEGIN
INSERT INTO SGS_CODE_VALUE
VALUES(52,'MSER','MSS Forms Path','http://10.100.104.108/forms/pension/',null,null,null,GETDATE(),null,1,null,'kunal.arora',GETDATE(),'kunal.arora',GETDATE(),0)
END


----added on 10th Oct 

/****** Object:  Table dbo.SGS_RESOURCES  ********/
IF NOT EXISTS (SELECT * FROM SGS_RESOURCES WHERE RESOURCE_ID = 199)
BEGIN
INSERT dbo.SGS_RESOURCES ([RESOURCE_ID],[RESOURCE_TYPE_ID],[RESOURCE_TYPE_VALUE],[RESOURCE_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(199,12,'F','Participant Portal','karora',GETDATE(),'karora',GETDATE(),0)
END


--sgs_roles
SET IDENTITY_INSERT [dbo].[SGS_roles] ON
GO
INSERT dbo.SGS_roles ([ROLE_ID],[ROLE_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
VALUES(500,'Participant Portal Access','karora',GETDATE(),'karora',GETDATE(),0)
GO
SET IDENTITY_INSERT [dbo].[SGS_roles] OFF
GO


declare @currentdatetime datetime
set @currentdatetime = '01/01/2013'
--sgs_user_roles
/****** Object:  Table dbo.sgs_user_roles  ********/
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(155,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(157,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(160,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(166,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(167,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(189,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(197,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(204,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(205,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(251,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(276,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(279,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(299,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(302,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(313,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(331,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(342,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(364,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(366,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(369,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(370,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(379,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(385,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(395,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(396,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.sgs_user_roles ([USER_SERIAL_ID],[ROLE_ID],[EFFECTIVE_START_DATE],[EFFECTIVE_END_DATE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(399,500,@currentdatetime,NULL,'karora',GETDATE(),'karora',GETDATE(),0)

delete from SGS_SECURITY where ROLE_ID = 500

INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(63,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(71,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(75,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(87,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(95,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(96,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(97,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(98,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(99,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(100,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(101,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(102,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(200,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(201,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(202,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(203,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(204,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(205,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(206,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(207,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(209,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(210,113,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(211,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(212,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(213,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(214,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(215,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(216,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(217,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(218,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(219,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(220,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(221,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(222,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(223,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(224,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(225,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(226,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(300,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(301,199,11,0,'karora',GETDATE(),'karora',GETDATE(),0)
INSERT dbo.SGS_SECURITY ([ROLE_ID],[RESOURCE_ID],[SECURITY_ID],[SECURITY_VALUE],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])VALUES(500,199,11,5,'karora',GETDATE(),'karora',GETDATE(),0)



----------------------------------------------------------------------------------------------------------------------------------
-- Name - Puneet Punjabi
-- Date - 10/22/2013
-- Purpose - Update the Forms Path for MSS
----------------------------------------------------------------------------------------------------------------------------------

IF EXISTS (SELECT * FROM SGS_CODE_VALUE WHERE CODE_ID = 52 and CODE_VALUE = 'MSER')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA1 = 'http://www.mpiphp.org/forms/pension/'
	WHERE CODE_ID = 52 AND CODE_VALUE = 'MSER'
END

