#region Using directives

using System;
using System.Collections;
using System.Collections.ObjectModel;
using System.Text;
using System.Data;
using Sagitec.Common;
using Sagitec.DBUtility;
using Sagitec.BusinessObjects;
using MPIPHP.CustomDataObjects;
using MPIPHP.DataObjects;

#endregion

namespace MPIPHP.BusinessObjects
{
    /// <summary>
    /// Class MPIPHP.BusinessObjects.busMPIAudit:
    /// Inherited from busMPIAuditGen, the class is used to customize the business object busMPIAuditGen.
    /// </summary>
    [Serializable]
    //FM upgrade: 6.0.1.2 changes - Changed the base class  from "busAudit" to "busAuditLog"
    public class busMPIAudit : busAuditLog
    {
        #region AutoGeneratedCode
        /// <summary>
        /// Constructor for MPIPHP.BusinessObjects.busMPIAuditGen
        /// </summary>
        //public busMPIAudit()
        //{

        //}

        ///// <summary>
        ///// Gets or sets the main-table object contained in busMPIAuditGen.
        ///// </summary>
        //public cdoAuditLog icdoAuditLog { get; set; }


        ///// <summary>
        ///// Gets or sets the collection object of type busAuditLogDetail. 
        ///// </summary>
        //public Collection<busAuditLogDetail> iclbAuditLogDetail { get; set; }



        ///// <summary>
        ///// MPIPHP.busMPIAuditGen.FindMPIAudit():
        ///// Finds a particular record from cdoAuditLog with its primary key. 
        ///// </summary>
        ///// <param name="aintauditlogid">A primary key value of type int of cdoAuditLog on which search is performed.</param>
        ///// <returns>true if found otherwise false</returns>
        //public virtual bool FindMPIAudit(int aintauditlogid)
        //{
        //    bool lblnResult = false;
        //    if (icdoAuditLog == null)
        //    {
        //        icdoAuditLog = new cdoAuditLog();
        //    }
        //    if (icdoAuditLog.SelectRow(new object[1] { aintauditlogid }))
        //    {
        //        lblnResult = true;
        //    }
        //    return lblnResult;
        //}

        ///// <summary>
        ///// MPIPHP.busMPIAuditGen.LoadAuditLogDetails():
        ///// Loads Collection object iclbAuditLogDetail of type busAuditLogDetail.
        ///// </summary>
        //public virtual void LoadAuditLogDetails()
        //{
        //    DataTable ldtbList = Select<cdoAuditLogDetail>(
        //        new string[1] { enmAuditLogDetail.audit_log_id.ToString() },
        //        new object[1] { icdoAuditLog.audit_log_id }, null, null);
        //    iclbAuditLogDetail = GetCollection<busAuditLogDetail>(ldtbList, "icdoAuditLogDetail");
        //}
        #endregion AutoGeneratedCode

        public busPerson ibusPerson {get;set;}

        public busPerson ibusOrganization { get; set; }

        public void LoadOrganization()
        {
            if (ibusOrganization == null)
            {
                ibusOrganization = new busPerson();
            }
            ibusOrganization.FindPerson(icdoAuditLog.org_id);
        }
    }
}


